import re, sys

src = open('/root/aom-rs/reference/libaom/av1/common/quant_common.c').read()

# Isolate the iwt_matrix_ref initializer: from its '= {' to the matching '};'
m = re.search(r'iwt_matrix_ref\[NUM_QM_LEVELS - 1\]\[2\]\[QM_TOTAL_SIZE\]\s*=\s*\{', src)
assert m, "iwt decl not found"
start = m.end() - 1  # position of the opening '{'
# brace-match
depth = 0
i = start
while i < len(src):
    c = src[i]
    if c == '{': depth += 1
    elif c == '}':
        depth -= 1
        if depth == 0:
            break
    i += 1
block = src[start:i+1]

# strip C comments /* ... */
block = re.sub(r'/\*.*?\*/', ' ', block, flags=re.DOTALL)
# strip preprocessor lines just in case
block = re.sub(r'^\s*#.*$', ' ', block, flags=re.MULTILINE)

nums = re.findall(r'-?\d+', block)
vals = [int(x) for x in nums]
QM_TOTAL_SIZE = 3344
LEVELS = 15  # NUM_QM_LEVELS - 1
PLANES = 2
expect = LEVELS * PLANES * QM_TOTAL_SIZE
print(f"parsed {len(vals)} values, expect {expect}", file=sys.stderr)
assert len(vals) == expect, f"count mismatch {len(vals)} != {expect}"
assert all(0 <= v <= 255 for v in vals), "value out of u8 range"

# emit nested Rust
out = []
out.append("// @generated by xtask/extract_qm_tables.py from")
out.append("// reference/libaom/av1/common/quant_common.c (libaom v3.14.1) —")
out.append("// `iwt_matrix_ref[NUM_QM_LEVELS-1][2][QM_TOTAL_SIZE]`, the inverse")
out.append("// quantization-matrix bases. Do not hand-edit; re-run the script.")
out.append("//")
out.append("// Layout: [qm_level 0..14][plane_group 0=luma/1=chroma][3344 packed]")
out.append("// The trailing (flat) level 15 is not stored — it selects `None`.")
out.append("#[rustfmt::skip]")
out.append(f"pub(crate) static IWT_MATRIX_REF: [[[u8; {QM_TOTAL_SIZE}]; {PLANES}]; {LEVELS}] = [")
idx = 0
for q in range(LEVELS):
    out.append("    [")
    for c in range(PLANES):
        row = vals[idx:idx+QM_TOTAL_SIZE]
        idx += QM_TOTAL_SIZE
        # wrap at ~24 per line
        body = []
        for k in range(0, QM_TOTAL_SIZE, 24):
            body.append("            " + ", ".join(str(x) for x in row[k:k+24]) + ",")
        out.append("        [")
        out.extend(body)
        out.append("        ],")
    out.append("    ],")
out.append("];")
open('/root/aom-rs/crates/aom-decode/src/qm_tables.rs','w').write("\n".join(out) + "\n")
print("wrote crates/aom-decode/src/qm_tables.rs", file=sys.stderr)
