import os, re, sys

# Repo-relative: this script lives in <repo>/xtask/.
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

src = open(os.path.join(REPO, 'reference/libaom/av1/common/quant_common.c')).read()

QM_TOTAL_SIZE = 3344
LEVELS = 15  # NUM_QM_LEVELS - 1
PLANES = 2


def extract(array_name):
    """Parse `<array_name>[NUM_QM_LEVELS - 1][2][QM_TOTAL_SIZE] = { ... }` from
    quant_common.c and return the flat list of LEVELS*PLANES*QM_TOTAL_SIZE u8s."""
    # NOTE the leading negative-lookbehind: `wt_matrix_ref` is a substring of
    # `iwt_matrix_ref`, so without it `re.search` would match the *inverse*
    # table's initializer (which appears first in the file) when asked for the
    # forward one, silently emitting inverse bytes. Require a non-identifier
    # char (or start-of-file) immediately before the name.
    m = re.search(
        r'(?<![A-Za-z0-9_])'
        + re.escape(array_name)
        + r'\[NUM_QM_LEVELS - 1\]\[2\]\[QM_TOTAL_SIZE\]\s*=\s*\{',
        src,
    )
    assert m, f"{array_name} decl not found"
    start = m.end() - 1  # position of the opening '{'
    # brace-match
    depth = 0
    i = start
    while i < len(src):
        c = src[i]
        if c == '{':
            depth += 1
        elif c == '}':
            depth -= 1
            if depth == 0:
                break
        i += 1
    block = src[start:i + 1]
    # strip C comments /* ... */ and preprocessor lines
    block = re.sub(r'/\*.*?\*/', ' ', block, flags=re.DOTALL)
    block = re.sub(r'^\s*#.*$', ' ', block, flags=re.MULTILINE)
    vals = [int(x) for x in re.findall(r'-?\d+', block)]
    expect = LEVELS * PLANES * QM_TOTAL_SIZE
    print(f"{array_name}: parsed {len(vals)} values, expect {expect}", file=sys.stderr)
    assert len(vals) == expect, f"count mismatch {len(vals)} != {expect}"
    assert all(0 <= v <= 255 for v in vals), "value out of u8 range"
    return vals


def emit(vals, rust_name, c_name, human, out_path):
    out = []
    out.append("// @generated by xtask/extract_qm_tables.py from")
    out.append("// reference/libaom/av1/common/quant_common.c (libaom v3.14.1) —")
    out.append(f"// `{c_name}[NUM_QM_LEVELS-1][2][QM_TOTAL_SIZE]`, the {human}")
    out.append("// quantization-matrix bases. Do not hand-edit; re-run the script.")
    out.append("//")
    out.append("// Layout: [qm_level 0..14][plane_group 0=luma/1=chroma][3344 packed]")
    out.append("// The trailing (flat) level 15 is not stored — it selects `None`.")
    out.append("#[rustfmt::skip]")
    out.append(f"pub(crate) static {rust_name}: [[[u8; {QM_TOTAL_SIZE}]; {PLANES}]; {LEVELS}] = [")
    idx = 0
    for _q in range(LEVELS):
        out.append("    [")
        for _c in range(PLANES):
            row = vals[idx:idx + QM_TOTAL_SIZE]
            idx += QM_TOTAL_SIZE
            out.append("        [")
            for k in range(0, QM_TOTAL_SIZE, 24):
                out.append("            " + ", ".join(str(x) for x in row[k:k + 24]) + ",")
            out.append("        ],")
        out.append("    ],")
    out.append("];")
    open(out_path, 'w').write("\n".join(out) + "\n")
    print(f"wrote {out_path}", file=sys.stderr)


# Both bases live in aom-dsp's quant module (one copy, shared by the encoder's
# forward/inverse quantize sites and — via `aom_decode::qm` — the dequantizer).
TARGETS = {
    'iwt': ('iwt_matrix_ref', 'IWT_MATRIX_REF', 'inverse',
            os.path.join(REPO, 'crates/aom-dsp/src/quant/qm_inv_tables.rs')),
    'wt': ('wt_matrix_ref', 'WT_MATRIX_REF', 'forward',
           os.path.join(REPO, 'crates/aom-dsp/src/quant/qm_fwd_tables.rs')),
}

which = sys.argv[1] if len(sys.argv) > 1 else 'iwt'
c_name, rust_name, human, out_path = TARGETS[which]
if len(sys.argv) > 2:
    out_path = sys.argv[2]
emit(extract(c_name), rust_name, c_name, human, out_path)
