//! GENERATED by xtask/transpile_txfm1d.py — do not edit by hand.
//! Bit-exact ports of libaom v3.14.1 ping-pong 1D inverse transforms.
#![allow(clippy::needless_range_loop)]
use crate::transform::cospi::cospi_arr;
use crate::transform::fdct::{clamp_value, half_btf};

/// Bit-exact port of libaom `av1_idct4` (transpiled, harness-verified).
#[allow(unused_variables)]
pub fn av1_idct4(input: &[i32], out: &mut [i32], cos_bit: i32, stage_range: &[i8]) {
    let cospi = cospi_arr(cos_bit);
    let mut step = [0i32; 4];
    out[0] = input[0];
    out[1] = input[2];
    out[2] = input[1];
    out[3] = input[3];
    step[0] = half_btf(cospi[32], out[0], cospi[32], out[1], cos_bit);
    step[1] = half_btf(cospi[32], out[0], -cospi[32], out[1], cos_bit);
    step[2] = half_btf(cospi[48], out[2], -cospi[16], out[3], cos_bit);
    step[3] = half_btf(cospi[16], out[2], cospi[48], out[3], cos_bit);
    out[0] = clamp_value(step[0].wrapping_add(step[3]), stage_range[3]);
    out[1] = clamp_value(step[1].wrapping_add(step[2]), stage_range[3]);
    out[2] = clamp_value(step[1].wrapping_sub(step[2]), stage_range[3]);
    out[3] = clamp_value(step[0].wrapping_sub(step[3]), stage_range[3]);
}

/// Bit-exact port of libaom `av1_idct8` (transpiled, harness-verified).
#[allow(unused_variables)]
pub fn av1_idct8(input: &[i32], out: &mut [i32], cos_bit: i32, stage_range: &[i8]) {
    let cospi = cospi_arr(cos_bit);
    let mut step = [0i32; 8];
    out[0] = input[0];
    out[1] = input[4];
    out[2] = input[2];
    out[3] = input[6];
    out[4] = input[1];
    out[5] = input[5];
    out[6] = input[3];
    out[7] = input[7];
    step[0] = out[0];
    step[1] = out[1];
    step[2] = out[2];
    step[3] = out[3];
    step[4] = half_btf(cospi[56], out[4], -cospi[8], out[7], cos_bit);
    step[5] = half_btf(cospi[24], out[5], -cospi[40], out[6], cos_bit);
    step[6] = half_btf(cospi[40], out[5], cospi[24], out[6], cos_bit);
    step[7] = half_btf(cospi[8], out[4], cospi[56], out[7], cos_bit);
    out[0] = half_btf(cospi[32], step[0], cospi[32], step[1], cos_bit);
    out[1] = half_btf(cospi[32], step[0], -cospi[32], step[1], cos_bit);
    out[2] = half_btf(cospi[48], step[2], -cospi[16], step[3], cos_bit);
    out[3] = half_btf(cospi[16], step[2], cospi[48], step[3], cos_bit);
    out[4] = clamp_value(step[4].wrapping_add(step[5]), stage_range[3]);
    out[5] = clamp_value(step[4].wrapping_sub(step[5]), stage_range[3]);
    out[6] = clamp_value(step[6].wrapping_neg().wrapping_add(step[7]), stage_range[3]);
    out[7] = clamp_value(step[6].wrapping_add(step[7]), stage_range[3]);
    step[0] = clamp_value(out[0].wrapping_add(out[3]), stage_range[4]);
    step[1] = clamp_value(out[1].wrapping_add(out[2]), stage_range[4]);
    step[2] = clamp_value(out[1].wrapping_sub(out[2]), stage_range[4]);
    step[3] = clamp_value(out[0].wrapping_sub(out[3]), stage_range[4]);
    step[4] = out[4];
    step[5] = half_btf(-cospi[32], out[5], cospi[32], out[6], cos_bit);
    step[6] = half_btf(cospi[32], out[5], cospi[32], out[6], cos_bit);
    step[7] = out[7];
    out[0] = clamp_value(step[0].wrapping_add(step[7]), stage_range[5]);
    out[1] = clamp_value(step[1].wrapping_add(step[6]), stage_range[5]);
    out[2] = clamp_value(step[2].wrapping_add(step[5]), stage_range[5]);
    out[3] = clamp_value(step[3].wrapping_add(step[4]), stage_range[5]);
    out[4] = clamp_value(step[3].wrapping_sub(step[4]), stage_range[5]);
    out[5] = clamp_value(step[2].wrapping_sub(step[5]), stage_range[5]);
    out[6] = clamp_value(step[1].wrapping_sub(step[6]), stage_range[5]);
    out[7] = clamp_value(step[0].wrapping_sub(step[7]), stage_range[5]);
}

/// Bit-exact port of libaom `av1_idct16` (transpiled, harness-verified).
#[allow(unused_variables)]
pub fn av1_idct16(input: &[i32], out: &mut [i32], cos_bit: i32, stage_range: &[i8]) {
    let cospi = cospi_arr(cos_bit);
    let mut step = [0i32; 16];
    out[0] = input[0];
    out[1] = input[8];
    out[2] = input[4];
    out[3] = input[12];
    out[4] = input[2];
    out[5] = input[10];
    out[6] = input[6];
    out[7] = input[14];
    out[8] = input[1];
    out[9] = input[9];
    out[10] = input[5];
    out[11] = input[13];
    out[12] = input[3];
    out[13] = input[11];
    out[14] = input[7];
    out[15] = input[15];
    step[0] = out[0];
    step[1] = out[1];
    step[2] = out[2];
    step[3] = out[3];
    step[4] = out[4];
    step[5] = out[5];
    step[6] = out[6];
    step[7] = out[7];
    step[8] = half_btf(cospi[60], out[8], -cospi[4], out[15], cos_bit);
    step[9] = half_btf(cospi[28], out[9], -cospi[36], out[14], cos_bit);
    step[10] = half_btf(cospi[44], out[10], -cospi[20], out[13], cos_bit);
    step[11] = half_btf(cospi[12], out[11], -cospi[52], out[12], cos_bit);
    step[12] = half_btf(cospi[52], out[11], cospi[12], out[12], cos_bit);
    step[13] = half_btf(cospi[20], out[10], cospi[44], out[13], cos_bit);
    step[14] = half_btf(cospi[36], out[9], cospi[28], out[14], cos_bit);
    step[15] = half_btf(cospi[4], out[8], cospi[60], out[15], cos_bit);
    out[0] = step[0];
    out[1] = step[1];
    out[2] = step[2];
    out[3] = step[3];
    out[4] = half_btf(cospi[56], step[4], -cospi[8], step[7], cos_bit);
    out[5] = half_btf(cospi[24], step[5], -cospi[40], step[6], cos_bit);
    out[6] = half_btf(cospi[40], step[5], cospi[24], step[6], cos_bit);
    out[7] = half_btf(cospi[8], step[4], cospi[56], step[7], cos_bit);
    out[8] = clamp_value(step[8].wrapping_add(step[9]), stage_range[3]);
    out[9] = clamp_value(step[8].wrapping_sub(step[9]), stage_range[3]);
    out[10] = clamp_value(
        step[10].wrapping_neg().wrapping_add(step[11]),
        stage_range[3],
    );
    out[11] = clamp_value(step[10].wrapping_add(step[11]), stage_range[3]);
    out[12] = clamp_value(step[12].wrapping_add(step[13]), stage_range[3]);
    out[13] = clamp_value(step[12].wrapping_sub(step[13]), stage_range[3]);
    out[14] = clamp_value(
        step[14].wrapping_neg().wrapping_add(step[15]),
        stage_range[3],
    );
    out[15] = clamp_value(step[14].wrapping_add(step[15]), stage_range[3]);
    step[0] = half_btf(cospi[32], out[0], cospi[32], out[1], cos_bit);
    step[1] = half_btf(cospi[32], out[0], -cospi[32], out[1], cos_bit);
    step[2] = half_btf(cospi[48], out[2], -cospi[16], out[3], cos_bit);
    step[3] = half_btf(cospi[16], out[2], cospi[48], out[3], cos_bit);
    step[4] = clamp_value(out[4].wrapping_add(out[5]), stage_range[4]);
    step[5] = clamp_value(out[4].wrapping_sub(out[5]), stage_range[4]);
    step[6] = clamp_value(out[6].wrapping_neg().wrapping_add(out[7]), stage_range[4]);
    step[7] = clamp_value(out[6].wrapping_add(out[7]), stage_range[4]);
    step[8] = out[8];
    step[9] = half_btf(-cospi[16], out[9], cospi[48], out[14], cos_bit);
    step[10] = half_btf(-cospi[48], out[10], -cospi[16], out[13], cos_bit);
    step[11] = out[11];
    step[12] = out[12];
    step[13] = half_btf(-cospi[16], out[10], cospi[48], out[13], cos_bit);
    step[14] = half_btf(cospi[48], out[9], cospi[16], out[14], cos_bit);
    step[15] = out[15];
    out[0] = clamp_value(step[0].wrapping_add(step[3]), stage_range[5]);
    out[1] = clamp_value(step[1].wrapping_add(step[2]), stage_range[5]);
    out[2] = clamp_value(step[1].wrapping_sub(step[2]), stage_range[5]);
    out[3] = clamp_value(step[0].wrapping_sub(step[3]), stage_range[5]);
    out[4] = step[4];
    out[5] = half_btf(-cospi[32], step[5], cospi[32], step[6], cos_bit);
    out[6] = half_btf(cospi[32], step[5], cospi[32], step[6], cos_bit);
    out[7] = step[7];
    out[8] = clamp_value(step[8].wrapping_add(step[11]), stage_range[5]);
    out[9] = clamp_value(step[9].wrapping_add(step[10]), stage_range[5]);
    out[10] = clamp_value(step[9].wrapping_sub(step[10]), stage_range[5]);
    out[11] = clamp_value(step[8].wrapping_sub(step[11]), stage_range[5]);
    out[12] = clamp_value(
        step[12].wrapping_neg().wrapping_add(step[15]),
        stage_range[5],
    );
    out[13] = clamp_value(
        step[13].wrapping_neg().wrapping_add(step[14]),
        stage_range[5],
    );
    out[14] = clamp_value(step[13].wrapping_add(step[14]), stage_range[5]);
    out[15] = clamp_value(step[12].wrapping_add(step[15]), stage_range[5]);
    step[0] = clamp_value(out[0].wrapping_add(out[7]), stage_range[6]);
    step[1] = clamp_value(out[1].wrapping_add(out[6]), stage_range[6]);
    step[2] = clamp_value(out[2].wrapping_add(out[5]), stage_range[6]);
    step[3] = clamp_value(out[3].wrapping_add(out[4]), stage_range[6]);
    step[4] = clamp_value(out[3].wrapping_sub(out[4]), stage_range[6]);
    step[5] = clamp_value(out[2].wrapping_sub(out[5]), stage_range[6]);
    step[6] = clamp_value(out[1].wrapping_sub(out[6]), stage_range[6]);
    step[7] = clamp_value(out[0].wrapping_sub(out[7]), stage_range[6]);
    step[8] = out[8];
    step[9] = out[9];
    step[10] = half_btf(-cospi[32], out[10], cospi[32], out[13], cos_bit);
    step[11] = half_btf(-cospi[32], out[11], cospi[32], out[12], cos_bit);
    step[12] = half_btf(cospi[32], out[11], cospi[32], out[12], cos_bit);
    step[13] = half_btf(cospi[32], out[10], cospi[32], out[13], cos_bit);
    step[14] = out[14];
    step[15] = out[15];
    out[0] = clamp_value(step[0].wrapping_add(step[15]), stage_range[7]);
    out[1] = clamp_value(step[1].wrapping_add(step[14]), stage_range[7]);
    out[2] = clamp_value(step[2].wrapping_add(step[13]), stage_range[7]);
    out[3] = clamp_value(step[3].wrapping_add(step[12]), stage_range[7]);
    out[4] = clamp_value(step[4].wrapping_add(step[11]), stage_range[7]);
    out[5] = clamp_value(step[5].wrapping_add(step[10]), stage_range[7]);
    out[6] = clamp_value(step[6].wrapping_add(step[9]), stage_range[7]);
    out[7] = clamp_value(step[7].wrapping_add(step[8]), stage_range[7]);
    out[8] = clamp_value(step[7].wrapping_sub(step[8]), stage_range[7]);
    out[9] = clamp_value(step[6].wrapping_sub(step[9]), stage_range[7]);
    out[10] = clamp_value(step[5].wrapping_sub(step[10]), stage_range[7]);
    out[11] = clamp_value(step[4].wrapping_sub(step[11]), stage_range[7]);
    out[12] = clamp_value(step[3].wrapping_sub(step[12]), stage_range[7]);
    out[13] = clamp_value(step[2].wrapping_sub(step[13]), stage_range[7]);
    out[14] = clamp_value(step[1].wrapping_sub(step[14]), stage_range[7]);
    out[15] = clamp_value(step[0].wrapping_sub(step[15]), stage_range[7]);
}

/// Bit-exact port of libaom `av1_idct32` (transpiled, harness-verified).
#[allow(unused_variables)]
pub fn av1_idct32(input: &[i32], out: &mut [i32], cos_bit: i32, stage_range: &[i8]) {
    let cospi = cospi_arr(cos_bit);
    let mut step = [0i32; 32];
    out[0] = input[0];
    out[1] = input[16];
    out[2] = input[8];
    out[3] = input[24];
    out[4] = input[4];
    out[5] = input[20];
    out[6] = input[12];
    out[7] = input[28];
    out[8] = input[2];
    out[9] = input[18];
    out[10] = input[10];
    out[11] = input[26];
    out[12] = input[6];
    out[13] = input[22];
    out[14] = input[14];
    out[15] = input[30];
    out[16] = input[1];
    out[17] = input[17];
    out[18] = input[9];
    out[19] = input[25];
    out[20] = input[5];
    out[21] = input[21];
    out[22] = input[13];
    out[23] = input[29];
    out[24] = input[3];
    out[25] = input[19];
    out[26] = input[11];
    out[27] = input[27];
    out[28] = input[7];
    out[29] = input[23];
    out[30] = input[15];
    out[31] = input[31];
    step[0] = out[0];
    step[1] = out[1];
    step[2] = out[2];
    step[3] = out[3];
    step[4] = out[4];
    step[5] = out[5];
    step[6] = out[6];
    step[7] = out[7];
    step[8] = out[8];
    step[9] = out[9];
    step[10] = out[10];
    step[11] = out[11];
    step[12] = out[12];
    step[13] = out[13];
    step[14] = out[14];
    step[15] = out[15];
    step[16] = half_btf(cospi[62], out[16], -cospi[2], out[31], cos_bit);
    step[17] = half_btf(cospi[30], out[17], -cospi[34], out[30], cos_bit);
    step[18] = half_btf(cospi[46], out[18], -cospi[18], out[29], cos_bit);
    step[19] = half_btf(cospi[14], out[19], -cospi[50], out[28], cos_bit);
    step[20] = half_btf(cospi[54], out[20], -cospi[10], out[27], cos_bit);
    step[21] = half_btf(cospi[22], out[21], -cospi[42], out[26], cos_bit);
    step[22] = half_btf(cospi[38], out[22], -cospi[26], out[25], cos_bit);
    step[23] = half_btf(cospi[6], out[23], -cospi[58], out[24], cos_bit);
    step[24] = half_btf(cospi[58], out[23], cospi[6], out[24], cos_bit);
    step[25] = half_btf(cospi[26], out[22], cospi[38], out[25], cos_bit);
    step[26] = half_btf(cospi[42], out[21], cospi[22], out[26], cos_bit);
    step[27] = half_btf(cospi[10], out[20], cospi[54], out[27], cos_bit);
    step[28] = half_btf(cospi[50], out[19], cospi[14], out[28], cos_bit);
    step[29] = half_btf(cospi[18], out[18], cospi[46], out[29], cos_bit);
    step[30] = half_btf(cospi[34], out[17], cospi[30], out[30], cos_bit);
    step[31] = half_btf(cospi[2], out[16], cospi[62], out[31], cos_bit);
    out[0] = step[0];
    out[1] = step[1];
    out[2] = step[2];
    out[3] = step[3];
    out[4] = step[4];
    out[5] = step[5];
    out[6] = step[6];
    out[7] = step[7];
    out[8] = half_btf(cospi[60], step[8], -cospi[4], step[15], cos_bit);
    out[9] = half_btf(cospi[28], step[9], -cospi[36], step[14], cos_bit);
    out[10] = half_btf(cospi[44], step[10], -cospi[20], step[13], cos_bit);
    out[11] = half_btf(cospi[12], step[11], -cospi[52], step[12], cos_bit);
    out[12] = half_btf(cospi[52], step[11], cospi[12], step[12], cos_bit);
    out[13] = half_btf(cospi[20], step[10], cospi[44], step[13], cos_bit);
    out[14] = half_btf(cospi[36], step[9], cospi[28], step[14], cos_bit);
    out[15] = half_btf(cospi[4], step[8], cospi[60], step[15], cos_bit);
    out[16] = clamp_value(step[16].wrapping_add(step[17]), stage_range[3]);
    out[17] = clamp_value(step[16].wrapping_sub(step[17]), stage_range[3]);
    out[18] = clamp_value(
        step[18].wrapping_neg().wrapping_add(step[19]),
        stage_range[3],
    );
    out[19] = clamp_value(step[18].wrapping_add(step[19]), stage_range[3]);
    out[20] = clamp_value(step[20].wrapping_add(step[21]), stage_range[3]);
    out[21] = clamp_value(step[20].wrapping_sub(step[21]), stage_range[3]);
    out[22] = clamp_value(
        step[22].wrapping_neg().wrapping_add(step[23]),
        stage_range[3],
    );
    out[23] = clamp_value(step[22].wrapping_add(step[23]), stage_range[3]);
    out[24] = clamp_value(step[24].wrapping_add(step[25]), stage_range[3]);
    out[25] = clamp_value(step[24].wrapping_sub(step[25]), stage_range[3]);
    out[26] = clamp_value(
        step[26].wrapping_neg().wrapping_add(step[27]),
        stage_range[3],
    );
    out[27] = clamp_value(step[26].wrapping_add(step[27]), stage_range[3]);
    out[28] = clamp_value(step[28].wrapping_add(step[29]), stage_range[3]);
    out[29] = clamp_value(step[28].wrapping_sub(step[29]), stage_range[3]);
    out[30] = clamp_value(
        step[30].wrapping_neg().wrapping_add(step[31]),
        stage_range[3],
    );
    out[31] = clamp_value(step[30].wrapping_add(step[31]), stage_range[3]);
    step[0] = out[0];
    step[1] = out[1];
    step[2] = out[2];
    step[3] = out[3];
    step[4] = half_btf(cospi[56], out[4], -cospi[8], out[7], cos_bit);
    step[5] = half_btf(cospi[24], out[5], -cospi[40], out[6], cos_bit);
    step[6] = half_btf(cospi[40], out[5], cospi[24], out[6], cos_bit);
    step[7] = half_btf(cospi[8], out[4], cospi[56], out[7], cos_bit);
    step[8] = clamp_value(out[8].wrapping_add(out[9]), stage_range[4]);
    step[9] = clamp_value(out[8].wrapping_sub(out[9]), stage_range[4]);
    step[10] = clamp_value(out[10].wrapping_neg().wrapping_add(out[11]), stage_range[4]);
    step[11] = clamp_value(out[10].wrapping_add(out[11]), stage_range[4]);
    step[12] = clamp_value(out[12].wrapping_add(out[13]), stage_range[4]);
    step[13] = clamp_value(out[12].wrapping_sub(out[13]), stage_range[4]);
    step[14] = clamp_value(out[14].wrapping_neg().wrapping_add(out[15]), stage_range[4]);
    step[15] = clamp_value(out[14].wrapping_add(out[15]), stage_range[4]);
    step[16] = out[16];
    step[17] = half_btf(-cospi[8], out[17], cospi[56], out[30], cos_bit);
    step[18] = half_btf(-cospi[56], out[18], -cospi[8], out[29], cos_bit);
    step[19] = out[19];
    step[20] = out[20];
    step[21] = half_btf(-cospi[40], out[21], cospi[24], out[26], cos_bit);
    step[22] = half_btf(-cospi[24], out[22], -cospi[40], out[25], cos_bit);
    step[23] = out[23];
    step[24] = out[24];
    step[25] = half_btf(-cospi[40], out[22], cospi[24], out[25], cos_bit);
    step[26] = half_btf(cospi[24], out[21], cospi[40], out[26], cos_bit);
    step[27] = out[27];
    step[28] = out[28];
    step[29] = half_btf(-cospi[8], out[18], cospi[56], out[29], cos_bit);
    step[30] = half_btf(cospi[56], out[17], cospi[8], out[30], cos_bit);
    step[31] = out[31];
    out[0] = half_btf(cospi[32], step[0], cospi[32], step[1], cos_bit);
    out[1] = half_btf(cospi[32], step[0], -cospi[32], step[1], cos_bit);
    out[2] = half_btf(cospi[48], step[2], -cospi[16], step[3], cos_bit);
    out[3] = half_btf(cospi[16], step[2], cospi[48], step[3], cos_bit);
    out[4] = clamp_value(step[4].wrapping_add(step[5]), stage_range[5]);
    out[5] = clamp_value(step[4].wrapping_sub(step[5]), stage_range[5]);
    out[6] = clamp_value(step[6].wrapping_neg().wrapping_add(step[7]), stage_range[5]);
    out[7] = clamp_value(step[6].wrapping_add(step[7]), stage_range[5]);
    out[8] = step[8];
    out[9] = half_btf(-cospi[16], step[9], cospi[48], step[14], cos_bit);
    out[10] = half_btf(-cospi[48], step[10], -cospi[16], step[13], cos_bit);
    out[11] = step[11];
    out[12] = step[12];
    out[13] = half_btf(-cospi[16], step[10], cospi[48], step[13], cos_bit);
    out[14] = half_btf(cospi[48], step[9], cospi[16], step[14], cos_bit);
    out[15] = step[15];
    out[16] = clamp_value(step[16].wrapping_add(step[19]), stage_range[5]);
    out[17] = clamp_value(step[17].wrapping_add(step[18]), stage_range[5]);
    out[18] = clamp_value(step[17].wrapping_sub(step[18]), stage_range[5]);
    out[19] = clamp_value(step[16].wrapping_sub(step[19]), stage_range[5]);
    out[20] = clamp_value(
        step[20].wrapping_neg().wrapping_add(step[23]),
        stage_range[5],
    );
    out[21] = clamp_value(
        step[21].wrapping_neg().wrapping_add(step[22]),
        stage_range[5],
    );
    out[22] = clamp_value(step[21].wrapping_add(step[22]), stage_range[5]);
    out[23] = clamp_value(step[20].wrapping_add(step[23]), stage_range[5]);
    out[24] = clamp_value(step[24].wrapping_add(step[27]), stage_range[5]);
    out[25] = clamp_value(step[25].wrapping_add(step[26]), stage_range[5]);
    out[26] = clamp_value(step[25].wrapping_sub(step[26]), stage_range[5]);
    out[27] = clamp_value(step[24].wrapping_sub(step[27]), stage_range[5]);
    out[28] = clamp_value(
        step[28].wrapping_neg().wrapping_add(step[31]),
        stage_range[5],
    );
    out[29] = clamp_value(
        step[29].wrapping_neg().wrapping_add(step[30]),
        stage_range[5],
    );
    out[30] = clamp_value(step[29].wrapping_add(step[30]), stage_range[5]);
    out[31] = clamp_value(step[28].wrapping_add(step[31]), stage_range[5]);
    step[0] = clamp_value(out[0].wrapping_add(out[3]), stage_range[6]);
    step[1] = clamp_value(out[1].wrapping_add(out[2]), stage_range[6]);
    step[2] = clamp_value(out[1].wrapping_sub(out[2]), stage_range[6]);
    step[3] = clamp_value(out[0].wrapping_sub(out[3]), stage_range[6]);
    step[4] = out[4];
    step[5] = half_btf(-cospi[32], out[5], cospi[32], out[6], cos_bit);
    step[6] = half_btf(cospi[32], out[5], cospi[32], out[6], cos_bit);
    step[7] = out[7];
    step[8] = clamp_value(out[8].wrapping_add(out[11]), stage_range[6]);
    step[9] = clamp_value(out[9].wrapping_add(out[10]), stage_range[6]);
    step[10] = clamp_value(out[9].wrapping_sub(out[10]), stage_range[6]);
    step[11] = clamp_value(out[8].wrapping_sub(out[11]), stage_range[6]);
    step[12] = clamp_value(out[12].wrapping_neg().wrapping_add(out[15]), stage_range[6]);
    step[13] = clamp_value(out[13].wrapping_neg().wrapping_add(out[14]), stage_range[6]);
    step[14] = clamp_value(out[13].wrapping_add(out[14]), stage_range[6]);
    step[15] = clamp_value(out[12].wrapping_add(out[15]), stage_range[6]);
    step[16] = out[16];
    step[17] = out[17];
    step[18] = half_btf(-cospi[16], out[18], cospi[48], out[29], cos_bit);
    step[19] = half_btf(-cospi[16], out[19], cospi[48], out[28], cos_bit);
    step[20] = half_btf(-cospi[48], out[20], -cospi[16], out[27], cos_bit);
    step[21] = half_btf(-cospi[48], out[21], -cospi[16], out[26], cos_bit);
    step[22] = out[22];
    step[23] = out[23];
    step[24] = out[24];
    step[25] = out[25];
    step[26] = half_btf(-cospi[16], out[21], cospi[48], out[26], cos_bit);
    step[27] = half_btf(-cospi[16], out[20], cospi[48], out[27], cos_bit);
    step[28] = half_btf(cospi[48], out[19], cospi[16], out[28], cos_bit);
    step[29] = half_btf(cospi[48], out[18], cospi[16], out[29], cos_bit);
    step[30] = out[30];
    step[31] = out[31];
    out[0] = clamp_value(step[0].wrapping_add(step[7]), stage_range[7]);
    out[1] = clamp_value(step[1].wrapping_add(step[6]), stage_range[7]);
    out[2] = clamp_value(step[2].wrapping_add(step[5]), stage_range[7]);
    out[3] = clamp_value(step[3].wrapping_add(step[4]), stage_range[7]);
    out[4] = clamp_value(step[3].wrapping_sub(step[4]), stage_range[7]);
    out[5] = clamp_value(step[2].wrapping_sub(step[5]), stage_range[7]);
    out[6] = clamp_value(step[1].wrapping_sub(step[6]), stage_range[7]);
    out[7] = clamp_value(step[0].wrapping_sub(step[7]), stage_range[7]);
    out[8] = step[8];
    out[9] = step[9];
    out[10] = half_btf(-cospi[32], step[10], cospi[32], step[13], cos_bit);
    out[11] = half_btf(-cospi[32], step[11], cospi[32], step[12], cos_bit);
    out[12] = half_btf(cospi[32], step[11], cospi[32], step[12], cos_bit);
    out[13] = half_btf(cospi[32], step[10], cospi[32], step[13], cos_bit);
    out[14] = step[14];
    out[15] = step[15];
    out[16] = clamp_value(step[16].wrapping_add(step[23]), stage_range[7]);
    out[17] = clamp_value(step[17].wrapping_add(step[22]), stage_range[7]);
    out[18] = clamp_value(step[18].wrapping_add(step[21]), stage_range[7]);
    out[19] = clamp_value(step[19].wrapping_add(step[20]), stage_range[7]);
    out[20] = clamp_value(step[19].wrapping_sub(step[20]), stage_range[7]);
    out[21] = clamp_value(step[18].wrapping_sub(step[21]), stage_range[7]);
    out[22] = clamp_value(step[17].wrapping_sub(step[22]), stage_range[7]);
    out[23] = clamp_value(step[16].wrapping_sub(step[23]), stage_range[7]);
    out[24] = clamp_value(
        step[24].wrapping_neg().wrapping_add(step[31]),
        stage_range[7],
    );
    out[25] = clamp_value(
        step[25].wrapping_neg().wrapping_add(step[30]),
        stage_range[7],
    );
    out[26] = clamp_value(
        step[26].wrapping_neg().wrapping_add(step[29]),
        stage_range[7],
    );
    out[27] = clamp_value(
        step[27].wrapping_neg().wrapping_add(step[28]),
        stage_range[7],
    );
    out[28] = clamp_value(step[27].wrapping_add(step[28]), stage_range[7]);
    out[29] = clamp_value(step[26].wrapping_add(step[29]), stage_range[7]);
    out[30] = clamp_value(step[25].wrapping_add(step[30]), stage_range[7]);
    out[31] = clamp_value(step[24].wrapping_add(step[31]), stage_range[7]);
    step[0] = clamp_value(out[0].wrapping_add(out[15]), stage_range[8]);
    step[1] = clamp_value(out[1].wrapping_add(out[14]), stage_range[8]);
    step[2] = clamp_value(out[2].wrapping_add(out[13]), stage_range[8]);
    step[3] = clamp_value(out[3].wrapping_add(out[12]), stage_range[8]);
    step[4] = clamp_value(out[4].wrapping_add(out[11]), stage_range[8]);
    step[5] = clamp_value(out[5].wrapping_add(out[10]), stage_range[8]);
    step[6] = clamp_value(out[6].wrapping_add(out[9]), stage_range[8]);
    step[7] = clamp_value(out[7].wrapping_add(out[8]), stage_range[8]);
    step[8] = clamp_value(out[7].wrapping_sub(out[8]), stage_range[8]);
    step[9] = clamp_value(out[6].wrapping_sub(out[9]), stage_range[8]);
    step[10] = clamp_value(out[5].wrapping_sub(out[10]), stage_range[8]);
    step[11] = clamp_value(out[4].wrapping_sub(out[11]), stage_range[8]);
    step[12] = clamp_value(out[3].wrapping_sub(out[12]), stage_range[8]);
    step[13] = clamp_value(out[2].wrapping_sub(out[13]), stage_range[8]);
    step[14] = clamp_value(out[1].wrapping_sub(out[14]), stage_range[8]);
    step[15] = clamp_value(out[0].wrapping_sub(out[15]), stage_range[8]);
    step[16] = out[16];
    step[17] = out[17];
    step[18] = out[18];
    step[19] = out[19];
    step[20] = half_btf(-cospi[32], out[20], cospi[32], out[27], cos_bit);
    step[21] = half_btf(-cospi[32], out[21], cospi[32], out[26], cos_bit);
    step[22] = half_btf(-cospi[32], out[22], cospi[32], out[25], cos_bit);
    step[23] = half_btf(-cospi[32], out[23], cospi[32], out[24], cos_bit);
    step[24] = half_btf(cospi[32], out[23], cospi[32], out[24], cos_bit);
    step[25] = half_btf(cospi[32], out[22], cospi[32], out[25], cos_bit);
    step[26] = half_btf(cospi[32], out[21], cospi[32], out[26], cos_bit);
    step[27] = half_btf(cospi[32], out[20], cospi[32], out[27], cos_bit);
    step[28] = out[28];
    step[29] = out[29];
    step[30] = out[30];
    step[31] = out[31];
    out[0] = clamp_value(step[0].wrapping_add(step[31]), stage_range[9]);
    out[1] = clamp_value(step[1].wrapping_add(step[30]), stage_range[9]);
    out[2] = clamp_value(step[2].wrapping_add(step[29]), stage_range[9]);
    out[3] = clamp_value(step[3].wrapping_add(step[28]), stage_range[9]);
    out[4] = clamp_value(step[4].wrapping_add(step[27]), stage_range[9]);
    out[5] = clamp_value(step[5].wrapping_add(step[26]), stage_range[9]);
    out[6] = clamp_value(step[6].wrapping_add(step[25]), stage_range[9]);
    out[7] = clamp_value(step[7].wrapping_add(step[24]), stage_range[9]);
    out[8] = clamp_value(step[8].wrapping_add(step[23]), stage_range[9]);
    out[9] = clamp_value(step[9].wrapping_add(step[22]), stage_range[9]);
    out[10] = clamp_value(step[10].wrapping_add(step[21]), stage_range[9]);
    out[11] = clamp_value(step[11].wrapping_add(step[20]), stage_range[9]);
    out[12] = clamp_value(step[12].wrapping_add(step[19]), stage_range[9]);
    out[13] = clamp_value(step[13].wrapping_add(step[18]), stage_range[9]);
    out[14] = clamp_value(step[14].wrapping_add(step[17]), stage_range[9]);
    out[15] = clamp_value(step[15].wrapping_add(step[16]), stage_range[9]);
    out[16] = clamp_value(step[15].wrapping_sub(step[16]), stage_range[9]);
    out[17] = clamp_value(step[14].wrapping_sub(step[17]), stage_range[9]);
    out[18] = clamp_value(step[13].wrapping_sub(step[18]), stage_range[9]);
    out[19] = clamp_value(step[12].wrapping_sub(step[19]), stage_range[9]);
    out[20] = clamp_value(step[11].wrapping_sub(step[20]), stage_range[9]);
    out[21] = clamp_value(step[10].wrapping_sub(step[21]), stage_range[9]);
    out[22] = clamp_value(step[9].wrapping_sub(step[22]), stage_range[9]);
    out[23] = clamp_value(step[8].wrapping_sub(step[23]), stage_range[9]);
    out[24] = clamp_value(step[7].wrapping_sub(step[24]), stage_range[9]);
    out[25] = clamp_value(step[6].wrapping_sub(step[25]), stage_range[9]);
    out[26] = clamp_value(step[5].wrapping_sub(step[26]), stage_range[9]);
    out[27] = clamp_value(step[4].wrapping_sub(step[27]), stage_range[9]);
    out[28] = clamp_value(step[3].wrapping_sub(step[28]), stage_range[9]);
    out[29] = clamp_value(step[2].wrapping_sub(step[29]), stage_range[9]);
    out[30] = clamp_value(step[1].wrapping_sub(step[30]), stage_range[9]);
    out[31] = clamp_value(step[0].wrapping_sub(step[31]), stage_range[9]);
}

/// Bit-exact port of libaom `av1_idct64` (transpiled, harness-verified).
#[allow(unused_variables)]
pub fn av1_idct64(input: &[i32], out: &mut [i32], cos_bit: i32, stage_range: &[i8]) {
    let cospi = cospi_arr(cos_bit);
    let mut step = [0i32; 64];
    out[0] = input[0];
    out[1] = input[32];
    out[2] = input[16];
    out[3] = input[48];
    out[4] = input[8];
    out[5] = input[40];
    out[6] = input[24];
    out[7] = input[56];
    out[8] = input[4];
    out[9] = input[36];
    out[10] = input[20];
    out[11] = input[52];
    out[12] = input[12];
    out[13] = input[44];
    out[14] = input[28];
    out[15] = input[60];
    out[16] = input[2];
    out[17] = input[34];
    out[18] = input[18];
    out[19] = input[50];
    out[20] = input[10];
    out[21] = input[42];
    out[22] = input[26];
    out[23] = input[58];
    out[24] = input[6];
    out[25] = input[38];
    out[26] = input[22];
    out[27] = input[54];
    out[28] = input[14];
    out[29] = input[46];
    out[30] = input[30];
    out[31] = input[62];
    out[32] = input[1];
    out[33] = input[33];
    out[34] = input[17];
    out[35] = input[49];
    out[36] = input[9];
    out[37] = input[41];
    out[38] = input[25];
    out[39] = input[57];
    out[40] = input[5];
    out[41] = input[37];
    out[42] = input[21];
    out[43] = input[53];
    out[44] = input[13];
    out[45] = input[45];
    out[46] = input[29];
    out[47] = input[61];
    out[48] = input[3];
    out[49] = input[35];
    out[50] = input[19];
    out[51] = input[51];
    out[52] = input[11];
    out[53] = input[43];
    out[54] = input[27];
    out[55] = input[59];
    out[56] = input[7];
    out[57] = input[39];
    out[58] = input[23];
    out[59] = input[55];
    out[60] = input[15];
    out[61] = input[47];
    out[62] = input[31];
    out[63] = input[63];
    step[0] = out[0];
    step[1] = out[1];
    step[2] = out[2];
    step[3] = out[3];
    step[4] = out[4];
    step[5] = out[5];
    step[6] = out[6];
    step[7] = out[7];
    step[8] = out[8];
    step[9] = out[9];
    step[10] = out[10];
    step[11] = out[11];
    step[12] = out[12];
    step[13] = out[13];
    step[14] = out[14];
    step[15] = out[15];
    step[16] = out[16];
    step[17] = out[17];
    step[18] = out[18];
    step[19] = out[19];
    step[20] = out[20];
    step[21] = out[21];
    step[22] = out[22];
    step[23] = out[23];
    step[24] = out[24];
    step[25] = out[25];
    step[26] = out[26];
    step[27] = out[27];
    step[28] = out[28];
    step[29] = out[29];
    step[30] = out[30];
    step[31] = out[31];
    step[32] = half_btf(cospi[63], out[32], -cospi[1], out[63], cos_bit);
    step[33] = half_btf(cospi[31], out[33], -cospi[33], out[62], cos_bit);
    step[34] = half_btf(cospi[47], out[34], -cospi[17], out[61], cos_bit);
    step[35] = half_btf(cospi[15], out[35], -cospi[49], out[60], cos_bit);
    step[36] = half_btf(cospi[55], out[36], -cospi[9], out[59], cos_bit);
    step[37] = half_btf(cospi[23], out[37], -cospi[41], out[58], cos_bit);
    step[38] = half_btf(cospi[39], out[38], -cospi[25], out[57], cos_bit);
    step[39] = half_btf(cospi[7], out[39], -cospi[57], out[56], cos_bit);
    step[40] = half_btf(cospi[59], out[40], -cospi[5], out[55], cos_bit);
    step[41] = half_btf(cospi[27], out[41], -cospi[37], out[54], cos_bit);
    step[42] = half_btf(cospi[43], out[42], -cospi[21], out[53], cos_bit);
    step[43] = half_btf(cospi[11], out[43], -cospi[53], out[52], cos_bit);
    step[44] = half_btf(cospi[51], out[44], -cospi[13], out[51], cos_bit);
    step[45] = half_btf(cospi[19], out[45], -cospi[45], out[50], cos_bit);
    step[46] = half_btf(cospi[35], out[46], -cospi[29], out[49], cos_bit);
    step[47] = half_btf(cospi[3], out[47], -cospi[61], out[48], cos_bit);
    step[48] = half_btf(cospi[61], out[47], cospi[3], out[48], cos_bit);
    step[49] = half_btf(cospi[29], out[46], cospi[35], out[49], cos_bit);
    step[50] = half_btf(cospi[45], out[45], cospi[19], out[50], cos_bit);
    step[51] = half_btf(cospi[13], out[44], cospi[51], out[51], cos_bit);
    step[52] = half_btf(cospi[53], out[43], cospi[11], out[52], cos_bit);
    step[53] = half_btf(cospi[21], out[42], cospi[43], out[53], cos_bit);
    step[54] = half_btf(cospi[37], out[41], cospi[27], out[54], cos_bit);
    step[55] = half_btf(cospi[5], out[40], cospi[59], out[55], cos_bit);
    step[56] = half_btf(cospi[57], out[39], cospi[7], out[56], cos_bit);
    step[57] = half_btf(cospi[25], out[38], cospi[39], out[57], cos_bit);
    step[58] = half_btf(cospi[41], out[37], cospi[23], out[58], cos_bit);
    step[59] = half_btf(cospi[9], out[36], cospi[55], out[59], cos_bit);
    step[60] = half_btf(cospi[49], out[35], cospi[15], out[60], cos_bit);
    step[61] = half_btf(cospi[17], out[34], cospi[47], out[61], cos_bit);
    step[62] = half_btf(cospi[33], out[33], cospi[31], out[62], cos_bit);
    step[63] = half_btf(cospi[1], out[32], cospi[63], out[63], cos_bit);
    out[0] = step[0];
    out[1] = step[1];
    out[2] = step[2];
    out[3] = step[3];
    out[4] = step[4];
    out[5] = step[5];
    out[6] = step[6];
    out[7] = step[7];
    out[8] = step[8];
    out[9] = step[9];
    out[10] = step[10];
    out[11] = step[11];
    out[12] = step[12];
    out[13] = step[13];
    out[14] = step[14];
    out[15] = step[15];
    out[16] = half_btf(cospi[62], step[16], -cospi[2], step[31], cos_bit);
    out[17] = half_btf(cospi[30], step[17], -cospi[34], step[30], cos_bit);
    out[18] = half_btf(cospi[46], step[18], -cospi[18], step[29], cos_bit);
    out[19] = half_btf(cospi[14], step[19], -cospi[50], step[28], cos_bit);
    out[20] = half_btf(cospi[54], step[20], -cospi[10], step[27], cos_bit);
    out[21] = half_btf(cospi[22], step[21], -cospi[42], step[26], cos_bit);
    out[22] = half_btf(cospi[38], step[22], -cospi[26], step[25], cos_bit);
    out[23] = half_btf(cospi[6], step[23], -cospi[58], step[24], cos_bit);
    out[24] = half_btf(cospi[58], step[23], cospi[6], step[24], cos_bit);
    out[25] = half_btf(cospi[26], step[22], cospi[38], step[25], cos_bit);
    out[26] = half_btf(cospi[42], step[21], cospi[22], step[26], cos_bit);
    out[27] = half_btf(cospi[10], step[20], cospi[54], step[27], cos_bit);
    out[28] = half_btf(cospi[50], step[19], cospi[14], step[28], cos_bit);
    out[29] = half_btf(cospi[18], step[18], cospi[46], step[29], cos_bit);
    out[30] = half_btf(cospi[34], step[17], cospi[30], step[30], cos_bit);
    out[31] = half_btf(cospi[2], step[16], cospi[62], step[31], cos_bit);
    out[32] = clamp_value(step[32].wrapping_add(step[33]), stage_range[3]);
    out[33] = clamp_value(step[32].wrapping_sub(step[33]), stage_range[3]);
    out[34] = clamp_value(
        step[34].wrapping_neg().wrapping_add(step[35]),
        stage_range[3],
    );
    out[35] = clamp_value(step[34].wrapping_add(step[35]), stage_range[3]);
    out[36] = clamp_value(step[36].wrapping_add(step[37]), stage_range[3]);
    out[37] = clamp_value(step[36].wrapping_sub(step[37]), stage_range[3]);
    out[38] = clamp_value(
        step[38].wrapping_neg().wrapping_add(step[39]),
        stage_range[3],
    );
    out[39] = clamp_value(step[38].wrapping_add(step[39]), stage_range[3]);
    out[40] = clamp_value(step[40].wrapping_add(step[41]), stage_range[3]);
    out[41] = clamp_value(step[40].wrapping_sub(step[41]), stage_range[3]);
    out[42] = clamp_value(
        step[42].wrapping_neg().wrapping_add(step[43]),
        stage_range[3],
    );
    out[43] = clamp_value(step[42].wrapping_add(step[43]), stage_range[3]);
    out[44] = clamp_value(step[44].wrapping_add(step[45]), stage_range[3]);
    out[45] = clamp_value(step[44].wrapping_sub(step[45]), stage_range[3]);
    out[46] = clamp_value(
        step[46].wrapping_neg().wrapping_add(step[47]),
        stage_range[3],
    );
    out[47] = clamp_value(step[46].wrapping_add(step[47]), stage_range[3]);
    out[48] = clamp_value(step[48].wrapping_add(step[49]), stage_range[3]);
    out[49] = clamp_value(step[48].wrapping_sub(step[49]), stage_range[3]);
    out[50] = clamp_value(
        step[50].wrapping_neg().wrapping_add(step[51]),
        stage_range[3],
    );
    out[51] = clamp_value(step[50].wrapping_add(step[51]), stage_range[3]);
    out[52] = clamp_value(step[52].wrapping_add(step[53]), stage_range[3]);
    out[53] = clamp_value(step[52].wrapping_sub(step[53]), stage_range[3]);
    out[54] = clamp_value(
        step[54].wrapping_neg().wrapping_add(step[55]),
        stage_range[3],
    );
    out[55] = clamp_value(step[54].wrapping_add(step[55]), stage_range[3]);
    out[56] = clamp_value(step[56].wrapping_add(step[57]), stage_range[3]);
    out[57] = clamp_value(step[56].wrapping_sub(step[57]), stage_range[3]);
    out[58] = clamp_value(
        step[58].wrapping_neg().wrapping_add(step[59]),
        stage_range[3],
    );
    out[59] = clamp_value(step[58].wrapping_add(step[59]), stage_range[3]);
    out[60] = clamp_value(step[60].wrapping_add(step[61]), stage_range[3]);
    out[61] = clamp_value(step[60].wrapping_sub(step[61]), stage_range[3]);
    out[62] = clamp_value(
        step[62].wrapping_neg().wrapping_add(step[63]),
        stage_range[3],
    );
    out[63] = clamp_value(step[62].wrapping_add(step[63]), stage_range[3]);
    step[0] = out[0];
    step[1] = out[1];
    step[2] = out[2];
    step[3] = out[3];
    step[4] = out[4];
    step[5] = out[5];
    step[6] = out[6];
    step[7] = out[7];
    step[8] = half_btf(cospi[60], out[8], -cospi[4], out[15], cos_bit);
    step[9] = half_btf(cospi[28], out[9], -cospi[36], out[14], cos_bit);
    step[10] = half_btf(cospi[44], out[10], -cospi[20], out[13], cos_bit);
    step[11] = half_btf(cospi[12], out[11], -cospi[52], out[12], cos_bit);
    step[12] = half_btf(cospi[52], out[11], cospi[12], out[12], cos_bit);
    step[13] = half_btf(cospi[20], out[10], cospi[44], out[13], cos_bit);
    step[14] = half_btf(cospi[36], out[9], cospi[28], out[14], cos_bit);
    step[15] = half_btf(cospi[4], out[8], cospi[60], out[15], cos_bit);
    step[16] = clamp_value(out[16].wrapping_add(out[17]), stage_range[4]);
    step[17] = clamp_value(out[16].wrapping_sub(out[17]), stage_range[4]);
    step[18] = clamp_value(out[18].wrapping_neg().wrapping_add(out[19]), stage_range[4]);
    step[19] = clamp_value(out[18].wrapping_add(out[19]), stage_range[4]);
    step[20] = clamp_value(out[20].wrapping_add(out[21]), stage_range[4]);
    step[21] = clamp_value(out[20].wrapping_sub(out[21]), stage_range[4]);
    step[22] = clamp_value(out[22].wrapping_neg().wrapping_add(out[23]), stage_range[4]);
    step[23] = clamp_value(out[22].wrapping_add(out[23]), stage_range[4]);
    step[24] = clamp_value(out[24].wrapping_add(out[25]), stage_range[4]);
    step[25] = clamp_value(out[24].wrapping_sub(out[25]), stage_range[4]);
    step[26] = clamp_value(out[26].wrapping_neg().wrapping_add(out[27]), stage_range[4]);
    step[27] = clamp_value(out[26].wrapping_add(out[27]), stage_range[4]);
    step[28] = clamp_value(out[28].wrapping_add(out[29]), stage_range[4]);
    step[29] = clamp_value(out[28].wrapping_sub(out[29]), stage_range[4]);
    step[30] = clamp_value(out[30].wrapping_neg().wrapping_add(out[31]), stage_range[4]);
    step[31] = clamp_value(out[30].wrapping_add(out[31]), stage_range[4]);
    step[32] = out[32];
    step[33] = half_btf(-cospi[4], out[33], cospi[60], out[62], cos_bit);
    step[34] = half_btf(-cospi[60], out[34], -cospi[4], out[61], cos_bit);
    step[35] = out[35];
    step[36] = out[36];
    step[37] = half_btf(-cospi[36], out[37], cospi[28], out[58], cos_bit);
    step[38] = half_btf(-cospi[28], out[38], -cospi[36], out[57], cos_bit);
    step[39] = out[39];
    step[40] = out[40];
    step[41] = half_btf(-cospi[20], out[41], cospi[44], out[54], cos_bit);
    step[42] = half_btf(-cospi[44], out[42], -cospi[20], out[53], cos_bit);
    step[43] = out[43];
    step[44] = out[44];
    step[45] = half_btf(-cospi[52], out[45], cospi[12], out[50], cos_bit);
    step[46] = half_btf(-cospi[12], out[46], -cospi[52], out[49], cos_bit);
    step[47] = out[47];
    step[48] = out[48];
    step[49] = half_btf(-cospi[52], out[46], cospi[12], out[49], cos_bit);
    step[50] = half_btf(cospi[12], out[45], cospi[52], out[50], cos_bit);
    step[51] = out[51];
    step[52] = out[52];
    step[53] = half_btf(-cospi[20], out[42], cospi[44], out[53], cos_bit);
    step[54] = half_btf(cospi[44], out[41], cospi[20], out[54], cos_bit);
    step[55] = out[55];
    step[56] = out[56];
    step[57] = half_btf(-cospi[36], out[38], cospi[28], out[57], cos_bit);
    step[58] = half_btf(cospi[28], out[37], cospi[36], out[58], cos_bit);
    step[59] = out[59];
    step[60] = out[60];
    step[61] = half_btf(-cospi[4], out[34], cospi[60], out[61], cos_bit);
    step[62] = half_btf(cospi[60], out[33], cospi[4], out[62], cos_bit);
    step[63] = out[63];
    out[0] = step[0];
    out[1] = step[1];
    out[2] = step[2];
    out[3] = step[3];
    out[4] = half_btf(cospi[56], step[4], -cospi[8], step[7], cos_bit);
    out[5] = half_btf(cospi[24], step[5], -cospi[40], step[6], cos_bit);
    out[6] = half_btf(cospi[40], step[5], cospi[24], step[6], cos_bit);
    out[7] = half_btf(cospi[8], step[4], cospi[56], step[7], cos_bit);
    out[8] = clamp_value(step[8].wrapping_add(step[9]), stage_range[5]);
    out[9] = clamp_value(step[8].wrapping_sub(step[9]), stage_range[5]);
    out[10] = clamp_value(
        step[10].wrapping_neg().wrapping_add(step[11]),
        stage_range[5],
    );
    out[11] = clamp_value(step[10].wrapping_add(step[11]), stage_range[5]);
    out[12] = clamp_value(step[12].wrapping_add(step[13]), stage_range[5]);
    out[13] = clamp_value(step[12].wrapping_sub(step[13]), stage_range[5]);
    out[14] = clamp_value(
        step[14].wrapping_neg().wrapping_add(step[15]),
        stage_range[5],
    );
    out[15] = clamp_value(step[14].wrapping_add(step[15]), stage_range[5]);
    out[16] = step[16];
    out[17] = half_btf(-cospi[8], step[17], cospi[56], step[30], cos_bit);
    out[18] = half_btf(-cospi[56], step[18], -cospi[8], step[29], cos_bit);
    out[19] = step[19];
    out[20] = step[20];
    out[21] = half_btf(-cospi[40], step[21], cospi[24], step[26], cos_bit);
    out[22] = half_btf(-cospi[24], step[22], -cospi[40], step[25], cos_bit);
    out[23] = step[23];
    out[24] = step[24];
    out[25] = half_btf(-cospi[40], step[22], cospi[24], step[25], cos_bit);
    out[26] = half_btf(cospi[24], step[21], cospi[40], step[26], cos_bit);
    out[27] = step[27];
    out[28] = step[28];
    out[29] = half_btf(-cospi[8], step[18], cospi[56], step[29], cos_bit);
    out[30] = half_btf(cospi[56], step[17], cospi[8], step[30], cos_bit);
    out[31] = step[31];
    out[32] = clamp_value(step[32].wrapping_add(step[35]), stage_range[5]);
    out[33] = clamp_value(step[33].wrapping_add(step[34]), stage_range[5]);
    out[34] = clamp_value(step[33].wrapping_sub(step[34]), stage_range[5]);
    out[35] = clamp_value(step[32].wrapping_sub(step[35]), stage_range[5]);
    out[36] = clamp_value(
        step[36].wrapping_neg().wrapping_add(step[39]),
        stage_range[5],
    );
    out[37] = clamp_value(
        step[37].wrapping_neg().wrapping_add(step[38]),
        stage_range[5],
    );
    out[38] = clamp_value(step[37].wrapping_add(step[38]), stage_range[5]);
    out[39] = clamp_value(step[36].wrapping_add(step[39]), stage_range[5]);
    out[40] = clamp_value(step[40].wrapping_add(step[43]), stage_range[5]);
    out[41] = clamp_value(step[41].wrapping_add(step[42]), stage_range[5]);
    out[42] = clamp_value(step[41].wrapping_sub(step[42]), stage_range[5]);
    out[43] = clamp_value(step[40].wrapping_sub(step[43]), stage_range[5]);
    out[44] = clamp_value(
        step[44].wrapping_neg().wrapping_add(step[47]),
        stage_range[5],
    );
    out[45] = clamp_value(
        step[45].wrapping_neg().wrapping_add(step[46]),
        stage_range[5],
    );
    out[46] = clamp_value(step[45].wrapping_add(step[46]), stage_range[5]);
    out[47] = clamp_value(step[44].wrapping_add(step[47]), stage_range[5]);
    out[48] = clamp_value(step[48].wrapping_add(step[51]), stage_range[5]);
    out[49] = clamp_value(step[49].wrapping_add(step[50]), stage_range[5]);
    out[50] = clamp_value(step[49].wrapping_sub(step[50]), stage_range[5]);
    out[51] = clamp_value(step[48].wrapping_sub(step[51]), stage_range[5]);
    out[52] = clamp_value(
        step[52].wrapping_neg().wrapping_add(step[55]),
        stage_range[5],
    );
    out[53] = clamp_value(
        step[53].wrapping_neg().wrapping_add(step[54]),
        stage_range[5],
    );
    out[54] = clamp_value(step[53].wrapping_add(step[54]), stage_range[5]);
    out[55] = clamp_value(step[52].wrapping_add(step[55]), stage_range[5]);
    out[56] = clamp_value(step[56].wrapping_add(step[59]), stage_range[5]);
    out[57] = clamp_value(step[57].wrapping_add(step[58]), stage_range[5]);
    out[58] = clamp_value(step[57].wrapping_sub(step[58]), stage_range[5]);
    out[59] = clamp_value(step[56].wrapping_sub(step[59]), stage_range[5]);
    out[60] = clamp_value(
        step[60].wrapping_neg().wrapping_add(step[63]),
        stage_range[5],
    );
    out[61] = clamp_value(
        step[61].wrapping_neg().wrapping_add(step[62]),
        stage_range[5],
    );
    out[62] = clamp_value(step[61].wrapping_add(step[62]), stage_range[5]);
    out[63] = clamp_value(step[60].wrapping_add(step[63]), stage_range[5]);
    step[0] = half_btf(cospi[32], out[0], cospi[32], out[1], cos_bit);
    step[1] = half_btf(cospi[32], out[0], -cospi[32], out[1], cos_bit);
    step[2] = half_btf(cospi[48], out[2], -cospi[16], out[3], cos_bit);
    step[3] = half_btf(cospi[16], out[2], cospi[48], out[3], cos_bit);
    step[4] = clamp_value(out[4].wrapping_add(out[5]), stage_range[6]);
    step[5] = clamp_value(out[4].wrapping_sub(out[5]), stage_range[6]);
    step[6] = clamp_value(out[6].wrapping_neg().wrapping_add(out[7]), stage_range[6]);
    step[7] = clamp_value(out[6].wrapping_add(out[7]), stage_range[6]);
    step[8] = out[8];
    step[9] = half_btf(-cospi[16], out[9], cospi[48], out[14], cos_bit);
    step[10] = half_btf(-cospi[48], out[10], -cospi[16], out[13], cos_bit);
    step[11] = out[11];
    step[12] = out[12];
    step[13] = half_btf(-cospi[16], out[10], cospi[48], out[13], cos_bit);
    step[14] = half_btf(cospi[48], out[9], cospi[16], out[14], cos_bit);
    step[15] = out[15];
    step[16] = clamp_value(out[16].wrapping_add(out[19]), stage_range[6]);
    step[17] = clamp_value(out[17].wrapping_add(out[18]), stage_range[6]);
    step[18] = clamp_value(out[17].wrapping_sub(out[18]), stage_range[6]);
    step[19] = clamp_value(out[16].wrapping_sub(out[19]), stage_range[6]);
    step[20] = clamp_value(out[20].wrapping_neg().wrapping_add(out[23]), stage_range[6]);
    step[21] = clamp_value(out[21].wrapping_neg().wrapping_add(out[22]), stage_range[6]);
    step[22] = clamp_value(out[21].wrapping_add(out[22]), stage_range[6]);
    step[23] = clamp_value(out[20].wrapping_add(out[23]), stage_range[6]);
    step[24] = clamp_value(out[24].wrapping_add(out[27]), stage_range[6]);
    step[25] = clamp_value(out[25].wrapping_add(out[26]), stage_range[6]);
    step[26] = clamp_value(out[25].wrapping_sub(out[26]), stage_range[6]);
    step[27] = clamp_value(out[24].wrapping_sub(out[27]), stage_range[6]);
    step[28] = clamp_value(out[28].wrapping_neg().wrapping_add(out[31]), stage_range[6]);
    step[29] = clamp_value(out[29].wrapping_neg().wrapping_add(out[30]), stage_range[6]);
    step[30] = clamp_value(out[29].wrapping_add(out[30]), stage_range[6]);
    step[31] = clamp_value(out[28].wrapping_add(out[31]), stage_range[6]);
    step[32] = out[32];
    step[33] = out[33];
    step[34] = half_btf(-cospi[8], out[34], cospi[56], out[61], cos_bit);
    step[35] = half_btf(-cospi[8], out[35], cospi[56], out[60], cos_bit);
    step[36] = half_btf(-cospi[56], out[36], -cospi[8], out[59], cos_bit);
    step[37] = half_btf(-cospi[56], out[37], -cospi[8], out[58], cos_bit);
    step[38] = out[38];
    step[39] = out[39];
    step[40] = out[40];
    step[41] = out[41];
    step[42] = half_btf(-cospi[40], out[42], cospi[24], out[53], cos_bit);
    step[43] = half_btf(-cospi[40], out[43], cospi[24], out[52], cos_bit);
    step[44] = half_btf(-cospi[24], out[44], -cospi[40], out[51], cos_bit);
    step[45] = half_btf(-cospi[24], out[45], -cospi[40], out[50], cos_bit);
    step[46] = out[46];
    step[47] = out[47];
    step[48] = out[48];
    step[49] = out[49];
    step[50] = half_btf(-cospi[40], out[45], cospi[24], out[50], cos_bit);
    step[51] = half_btf(-cospi[40], out[44], cospi[24], out[51], cos_bit);
    step[52] = half_btf(cospi[24], out[43], cospi[40], out[52], cos_bit);
    step[53] = half_btf(cospi[24], out[42], cospi[40], out[53], cos_bit);
    step[54] = out[54];
    step[55] = out[55];
    step[56] = out[56];
    step[57] = out[57];
    step[58] = half_btf(-cospi[8], out[37], cospi[56], out[58], cos_bit);
    step[59] = half_btf(-cospi[8], out[36], cospi[56], out[59], cos_bit);
    step[60] = half_btf(cospi[56], out[35], cospi[8], out[60], cos_bit);
    step[61] = half_btf(cospi[56], out[34], cospi[8], out[61], cos_bit);
    step[62] = out[62];
    step[63] = out[63];
    out[0] = clamp_value(step[0].wrapping_add(step[3]), stage_range[7]);
    out[1] = clamp_value(step[1].wrapping_add(step[2]), stage_range[7]);
    out[2] = clamp_value(step[1].wrapping_sub(step[2]), stage_range[7]);
    out[3] = clamp_value(step[0].wrapping_sub(step[3]), stage_range[7]);
    out[4] = step[4];
    out[5] = half_btf(-cospi[32], step[5], cospi[32], step[6], cos_bit);
    out[6] = half_btf(cospi[32], step[5], cospi[32], step[6], cos_bit);
    out[7] = step[7];
    out[8] = clamp_value(step[8].wrapping_add(step[11]), stage_range[7]);
    out[9] = clamp_value(step[9].wrapping_add(step[10]), stage_range[7]);
    out[10] = clamp_value(step[9].wrapping_sub(step[10]), stage_range[7]);
    out[11] = clamp_value(step[8].wrapping_sub(step[11]), stage_range[7]);
    out[12] = clamp_value(
        step[12].wrapping_neg().wrapping_add(step[15]),
        stage_range[7],
    );
    out[13] = clamp_value(
        step[13].wrapping_neg().wrapping_add(step[14]),
        stage_range[7],
    );
    out[14] = clamp_value(step[13].wrapping_add(step[14]), stage_range[7]);
    out[15] = clamp_value(step[12].wrapping_add(step[15]), stage_range[7]);
    out[16] = step[16];
    out[17] = step[17];
    out[18] = half_btf(-cospi[16], step[18], cospi[48], step[29], cos_bit);
    out[19] = half_btf(-cospi[16], step[19], cospi[48], step[28], cos_bit);
    out[20] = half_btf(-cospi[48], step[20], -cospi[16], step[27], cos_bit);
    out[21] = half_btf(-cospi[48], step[21], -cospi[16], step[26], cos_bit);
    out[22] = step[22];
    out[23] = step[23];
    out[24] = step[24];
    out[25] = step[25];
    out[26] = half_btf(-cospi[16], step[21], cospi[48], step[26], cos_bit);
    out[27] = half_btf(-cospi[16], step[20], cospi[48], step[27], cos_bit);
    out[28] = half_btf(cospi[48], step[19], cospi[16], step[28], cos_bit);
    out[29] = half_btf(cospi[48], step[18], cospi[16], step[29], cos_bit);
    out[30] = step[30];
    out[31] = step[31];
    out[32] = clamp_value(step[32].wrapping_add(step[39]), stage_range[7]);
    out[33] = clamp_value(step[33].wrapping_add(step[38]), stage_range[7]);
    out[34] = clamp_value(step[34].wrapping_add(step[37]), stage_range[7]);
    out[35] = clamp_value(step[35].wrapping_add(step[36]), stage_range[7]);
    out[36] = clamp_value(step[35].wrapping_sub(step[36]), stage_range[7]);
    out[37] = clamp_value(step[34].wrapping_sub(step[37]), stage_range[7]);
    out[38] = clamp_value(step[33].wrapping_sub(step[38]), stage_range[7]);
    out[39] = clamp_value(step[32].wrapping_sub(step[39]), stage_range[7]);
    out[40] = clamp_value(
        step[40].wrapping_neg().wrapping_add(step[47]),
        stage_range[7],
    );
    out[41] = clamp_value(
        step[41].wrapping_neg().wrapping_add(step[46]),
        stage_range[7],
    );
    out[42] = clamp_value(
        step[42].wrapping_neg().wrapping_add(step[45]),
        stage_range[7],
    );
    out[43] = clamp_value(
        step[43].wrapping_neg().wrapping_add(step[44]),
        stage_range[7],
    );
    out[44] = clamp_value(step[43].wrapping_add(step[44]), stage_range[7]);
    out[45] = clamp_value(step[42].wrapping_add(step[45]), stage_range[7]);
    out[46] = clamp_value(step[41].wrapping_add(step[46]), stage_range[7]);
    out[47] = clamp_value(step[40].wrapping_add(step[47]), stage_range[7]);
    out[48] = clamp_value(step[48].wrapping_add(step[55]), stage_range[7]);
    out[49] = clamp_value(step[49].wrapping_add(step[54]), stage_range[7]);
    out[50] = clamp_value(step[50].wrapping_add(step[53]), stage_range[7]);
    out[51] = clamp_value(step[51].wrapping_add(step[52]), stage_range[7]);
    out[52] = clamp_value(step[51].wrapping_sub(step[52]), stage_range[7]);
    out[53] = clamp_value(step[50].wrapping_sub(step[53]), stage_range[7]);
    out[54] = clamp_value(step[49].wrapping_sub(step[54]), stage_range[7]);
    out[55] = clamp_value(step[48].wrapping_sub(step[55]), stage_range[7]);
    out[56] = clamp_value(
        step[56].wrapping_neg().wrapping_add(step[63]),
        stage_range[7],
    );
    out[57] = clamp_value(
        step[57].wrapping_neg().wrapping_add(step[62]),
        stage_range[7],
    );
    out[58] = clamp_value(
        step[58].wrapping_neg().wrapping_add(step[61]),
        stage_range[7],
    );
    out[59] = clamp_value(
        step[59].wrapping_neg().wrapping_add(step[60]),
        stage_range[7],
    );
    out[60] = clamp_value(step[59].wrapping_add(step[60]), stage_range[7]);
    out[61] = clamp_value(step[58].wrapping_add(step[61]), stage_range[7]);
    out[62] = clamp_value(step[57].wrapping_add(step[62]), stage_range[7]);
    out[63] = clamp_value(step[56].wrapping_add(step[63]), stage_range[7]);
    step[0] = clamp_value(out[0].wrapping_add(out[7]), stage_range[8]);
    step[1] = clamp_value(out[1].wrapping_add(out[6]), stage_range[8]);
    step[2] = clamp_value(out[2].wrapping_add(out[5]), stage_range[8]);
    step[3] = clamp_value(out[3].wrapping_add(out[4]), stage_range[8]);
    step[4] = clamp_value(out[3].wrapping_sub(out[4]), stage_range[8]);
    step[5] = clamp_value(out[2].wrapping_sub(out[5]), stage_range[8]);
    step[6] = clamp_value(out[1].wrapping_sub(out[6]), stage_range[8]);
    step[7] = clamp_value(out[0].wrapping_sub(out[7]), stage_range[8]);
    step[8] = out[8];
    step[9] = out[9];
    step[10] = half_btf(-cospi[32], out[10], cospi[32], out[13], cos_bit);
    step[11] = half_btf(-cospi[32], out[11], cospi[32], out[12], cos_bit);
    step[12] = half_btf(cospi[32], out[11], cospi[32], out[12], cos_bit);
    step[13] = half_btf(cospi[32], out[10], cospi[32], out[13], cos_bit);
    step[14] = out[14];
    step[15] = out[15];
    step[16] = clamp_value(out[16].wrapping_add(out[23]), stage_range[8]);
    step[17] = clamp_value(out[17].wrapping_add(out[22]), stage_range[8]);
    step[18] = clamp_value(out[18].wrapping_add(out[21]), stage_range[8]);
    step[19] = clamp_value(out[19].wrapping_add(out[20]), stage_range[8]);
    step[20] = clamp_value(out[19].wrapping_sub(out[20]), stage_range[8]);
    step[21] = clamp_value(out[18].wrapping_sub(out[21]), stage_range[8]);
    step[22] = clamp_value(out[17].wrapping_sub(out[22]), stage_range[8]);
    step[23] = clamp_value(out[16].wrapping_sub(out[23]), stage_range[8]);
    step[24] = clamp_value(out[24].wrapping_neg().wrapping_add(out[31]), stage_range[8]);
    step[25] = clamp_value(out[25].wrapping_neg().wrapping_add(out[30]), stage_range[8]);
    step[26] = clamp_value(out[26].wrapping_neg().wrapping_add(out[29]), stage_range[8]);
    step[27] = clamp_value(out[27].wrapping_neg().wrapping_add(out[28]), stage_range[8]);
    step[28] = clamp_value(out[27].wrapping_add(out[28]), stage_range[8]);
    step[29] = clamp_value(out[26].wrapping_add(out[29]), stage_range[8]);
    step[30] = clamp_value(out[25].wrapping_add(out[30]), stage_range[8]);
    step[31] = clamp_value(out[24].wrapping_add(out[31]), stage_range[8]);
    step[32] = out[32];
    step[33] = out[33];
    step[34] = out[34];
    step[35] = out[35];
    step[36] = half_btf(-cospi[16], out[36], cospi[48], out[59], cos_bit);
    step[37] = half_btf(-cospi[16], out[37], cospi[48], out[58], cos_bit);
    step[38] = half_btf(-cospi[16], out[38], cospi[48], out[57], cos_bit);
    step[39] = half_btf(-cospi[16], out[39], cospi[48], out[56], cos_bit);
    step[40] = half_btf(-cospi[48], out[40], -cospi[16], out[55], cos_bit);
    step[41] = half_btf(-cospi[48], out[41], -cospi[16], out[54], cos_bit);
    step[42] = half_btf(-cospi[48], out[42], -cospi[16], out[53], cos_bit);
    step[43] = half_btf(-cospi[48], out[43], -cospi[16], out[52], cos_bit);
    step[44] = out[44];
    step[45] = out[45];
    step[46] = out[46];
    step[47] = out[47];
    step[48] = out[48];
    step[49] = out[49];
    step[50] = out[50];
    step[51] = out[51];
    step[52] = half_btf(-cospi[16], out[43], cospi[48], out[52], cos_bit);
    step[53] = half_btf(-cospi[16], out[42], cospi[48], out[53], cos_bit);
    step[54] = half_btf(-cospi[16], out[41], cospi[48], out[54], cos_bit);
    step[55] = half_btf(-cospi[16], out[40], cospi[48], out[55], cos_bit);
    step[56] = half_btf(cospi[48], out[39], cospi[16], out[56], cos_bit);
    step[57] = half_btf(cospi[48], out[38], cospi[16], out[57], cos_bit);
    step[58] = half_btf(cospi[48], out[37], cospi[16], out[58], cos_bit);
    step[59] = half_btf(cospi[48], out[36], cospi[16], out[59], cos_bit);
    step[60] = out[60];
    step[61] = out[61];
    step[62] = out[62];
    step[63] = out[63];
    out[0] = clamp_value(step[0].wrapping_add(step[15]), stage_range[9]);
    out[1] = clamp_value(step[1].wrapping_add(step[14]), stage_range[9]);
    out[2] = clamp_value(step[2].wrapping_add(step[13]), stage_range[9]);
    out[3] = clamp_value(step[3].wrapping_add(step[12]), stage_range[9]);
    out[4] = clamp_value(step[4].wrapping_add(step[11]), stage_range[9]);
    out[5] = clamp_value(step[5].wrapping_add(step[10]), stage_range[9]);
    out[6] = clamp_value(step[6].wrapping_add(step[9]), stage_range[9]);
    out[7] = clamp_value(step[7].wrapping_add(step[8]), stage_range[9]);
    out[8] = clamp_value(step[7].wrapping_sub(step[8]), stage_range[9]);
    out[9] = clamp_value(step[6].wrapping_sub(step[9]), stage_range[9]);
    out[10] = clamp_value(step[5].wrapping_sub(step[10]), stage_range[9]);
    out[11] = clamp_value(step[4].wrapping_sub(step[11]), stage_range[9]);
    out[12] = clamp_value(step[3].wrapping_sub(step[12]), stage_range[9]);
    out[13] = clamp_value(step[2].wrapping_sub(step[13]), stage_range[9]);
    out[14] = clamp_value(step[1].wrapping_sub(step[14]), stage_range[9]);
    out[15] = clamp_value(step[0].wrapping_sub(step[15]), stage_range[9]);
    out[16] = step[16];
    out[17] = step[17];
    out[18] = step[18];
    out[19] = step[19];
    out[20] = half_btf(-cospi[32], step[20], cospi[32], step[27], cos_bit);
    out[21] = half_btf(-cospi[32], step[21], cospi[32], step[26], cos_bit);
    out[22] = half_btf(-cospi[32], step[22], cospi[32], step[25], cos_bit);
    out[23] = half_btf(-cospi[32], step[23], cospi[32], step[24], cos_bit);
    out[24] = half_btf(cospi[32], step[23], cospi[32], step[24], cos_bit);
    out[25] = half_btf(cospi[32], step[22], cospi[32], step[25], cos_bit);
    out[26] = half_btf(cospi[32], step[21], cospi[32], step[26], cos_bit);
    out[27] = half_btf(cospi[32], step[20], cospi[32], step[27], cos_bit);
    out[28] = step[28];
    out[29] = step[29];
    out[30] = step[30];
    out[31] = step[31];
    out[32] = clamp_value(step[32].wrapping_add(step[47]), stage_range[9]);
    out[33] = clamp_value(step[33].wrapping_add(step[46]), stage_range[9]);
    out[34] = clamp_value(step[34].wrapping_add(step[45]), stage_range[9]);
    out[35] = clamp_value(step[35].wrapping_add(step[44]), stage_range[9]);
    out[36] = clamp_value(step[36].wrapping_add(step[43]), stage_range[9]);
    out[37] = clamp_value(step[37].wrapping_add(step[42]), stage_range[9]);
    out[38] = clamp_value(step[38].wrapping_add(step[41]), stage_range[9]);
    out[39] = clamp_value(step[39].wrapping_add(step[40]), stage_range[9]);
    out[40] = clamp_value(step[39].wrapping_sub(step[40]), stage_range[9]);
    out[41] = clamp_value(step[38].wrapping_sub(step[41]), stage_range[9]);
    out[42] = clamp_value(step[37].wrapping_sub(step[42]), stage_range[9]);
    out[43] = clamp_value(step[36].wrapping_sub(step[43]), stage_range[9]);
    out[44] = clamp_value(step[35].wrapping_sub(step[44]), stage_range[9]);
    out[45] = clamp_value(step[34].wrapping_sub(step[45]), stage_range[9]);
    out[46] = clamp_value(step[33].wrapping_sub(step[46]), stage_range[9]);
    out[47] = clamp_value(step[32].wrapping_sub(step[47]), stage_range[9]);
    out[48] = clamp_value(
        step[48].wrapping_neg().wrapping_add(step[63]),
        stage_range[9],
    );
    out[49] = clamp_value(
        step[49].wrapping_neg().wrapping_add(step[62]),
        stage_range[9],
    );
    out[50] = clamp_value(
        step[50].wrapping_neg().wrapping_add(step[61]),
        stage_range[9],
    );
    out[51] = clamp_value(
        step[51].wrapping_neg().wrapping_add(step[60]),
        stage_range[9],
    );
    out[52] = clamp_value(
        step[52].wrapping_neg().wrapping_add(step[59]),
        stage_range[9],
    );
    out[53] = clamp_value(
        step[53].wrapping_neg().wrapping_add(step[58]),
        stage_range[9],
    );
    out[54] = clamp_value(
        step[54].wrapping_neg().wrapping_add(step[57]),
        stage_range[9],
    );
    out[55] = clamp_value(
        step[55].wrapping_neg().wrapping_add(step[56]),
        stage_range[9],
    );
    out[56] = clamp_value(step[55].wrapping_add(step[56]), stage_range[9]);
    out[57] = clamp_value(step[54].wrapping_add(step[57]), stage_range[9]);
    out[58] = clamp_value(step[53].wrapping_add(step[58]), stage_range[9]);
    out[59] = clamp_value(step[52].wrapping_add(step[59]), stage_range[9]);
    out[60] = clamp_value(step[51].wrapping_add(step[60]), stage_range[9]);
    out[61] = clamp_value(step[50].wrapping_add(step[61]), stage_range[9]);
    out[62] = clamp_value(step[49].wrapping_add(step[62]), stage_range[9]);
    out[63] = clamp_value(step[48].wrapping_add(step[63]), stage_range[9]);
    step[0] = clamp_value(out[0].wrapping_add(out[31]), stage_range[10]);
    step[1] = clamp_value(out[1].wrapping_add(out[30]), stage_range[10]);
    step[2] = clamp_value(out[2].wrapping_add(out[29]), stage_range[10]);
    step[3] = clamp_value(out[3].wrapping_add(out[28]), stage_range[10]);
    step[4] = clamp_value(out[4].wrapping_add(out[27]), stage_range[10]);
    step[5] = clamp_value(out[5].wrapping_add(out[26]), stage_range[10]);
    step[6] = clamp_value(out[6].wrapping_add(out[25]), stage_range[10]);
    step[7] = clamp_value(out[7].wrapping_add(out[24]), stage_range[10]);
    step[8] = clamp_value(out[8].wrapping_add(out[23]), stage_range[10]);
    step[9] = clamp_value(out[9].wrapping_add(out[22]), stage_range[10]);
    step[10] = clamp_value(out[10].wrapping_add(out[21]), stage_range[10]);
    step[11] = clamp_value(out[11].wrapping_add(out[20]), stage_range[10]);
    step[12] = clamp_value(out[12].wrapping_add(out[19]), stage_range[10]);
    step[13] = clamp_value(out[13].wrapping_add(out[18]), stage_range[10]);
    step[14] = clamp_value(out[14].wrapping_add(out[17]), stage_range[10]);
    step[15] = clamp_value(out[15].wrapping_add(out[16]), stage_range[10]);
    step[16] = clamp_value(out[15].wrapping_sub(out[16]), stage_range[10]);
    step[17] = clamp_value(out[14].wrapping_sub(out[17]), stage_range[10]);
    step[18] = clamp_value(out[13].wrapping_sub(out[18]), stage_range[10]);
    step[19] = clamp_value(out[12].wrapping_sub(out[19]), stage_range[10]);
    step[20] = clamp_value(out[11].wrapping_sub(out[20]), stage_range[10]);
    step[21] = clamp_value(out[10].wrapping_sub(out[21]), stage_range[10]);
    step[22] = clamp_value(out[9].wrapping_sub(out[22]), stage_range[10]);
    step[23] = clamp_value(out[8].wrapping_sub(out[23]), stage_range[10]);
    step[24] = clamp_value(out[7].wrapping_sub(out[24]), stage_range[10]);
    step[25] = clamp_value(out[6].wrapping_sub(out[25]), stage_range[10]);
    step[26] = clamp_value(out[5].wrapping_sub(out[26]), stage_range[10]);
    step[27] = clamp_value(out[4].wrapping_sub(out[27]), stage_range[10]);
    step[28] = clamp_value(out[3].wrapping_sub(out[28]), stage_range[10]);
    step[29] = clamp_value(out[2].wrapping_sub(out[29]), stage_range[10]);
    step[30] = clamp_value(out[1].wrapping_sub(out[30]), stage_range[10]);
    step[31] = clamp_value(out[0].wrapping_sub(out[31]), stage_range[10]);
    step[32] = out[32];
    step[33] = out[33];
    step[34] = out[34];
    step[35] = out[35];
    step[36] = out[36];
    step[37] = out[37];
    step[38] = out[38];
    step[39] = out[39];
    step[40] = half_btf(-cospi[32], out[40], cospi[32], out[55], cos_bit);
    step[41] = half_btf(-cospi[32], out[41], cospi[32], out[54], cos_bit);
    step[42] = half_btf(-cospi[32], out[42], cospi[32], out[53], cos_bit);
    step[43] = half_btf(-cospi[32], out[43], cospi[32], out[52], cos_bit);
    step[44] = half_btf(-cospi[32], out[44], cospi[32], out[51], cos_bit);
    step[45] = half_btf(-cospi[32], out[45], cospi[32], out[50], cos_bit);
    step[46] = half_btf(-cospi[32], out[46], cospi[32], out[49], cos_bit);
    step[47] = half_btf(-cospi[32], out[47], cospi[32], out[48], cos_bit);
    step[48] = half_btf(cospi[32], out[47], cospi[32], out[48], cos_bit);
    step[49] = half_btf(cospi[32], out[46], cospi[32], out[49], cos_bit);
    step[50] = half_btf(cospi[32], out[45], cospi[32], out[50], cos_bit);
    step[51] = half_btf(cospi[32], out[44], cospi[32], out[51], cos_bit);
    step[52] = half_btf(cospi[32], out[43], cospi[32], out[52], cos_bit);
    step[53] = half_btf(cospi[32], out[42], cospi[32], out[53], cos_bit);
    step[54] = half_btf(cospi[32], out[41], cospi[32], out[54], cos_bit);
    step[55] = half_btf(cospi[32], out[40], cospi[32], out[55], cos_bit);
    step[56] = out[56];
    step[57] = out[57];
    step[58] = out[58];
    step[59] = out[59];
    step[60] = out[60];
    step[61] = out[61];
    step[62] = out[62];
    step[63] = out[63];
    out[0] = clamp_value(step[0].wrapping_add(step[63]), stage_range[11]);
    out[1] = clamp_value(step[1].wrapping_add(step[62]), stage_range[11]);
    out[2] = clamp_value(step[2].wrapping_add(step[61]), stage_range[11]);
    out[3] = clamp_value(step[3].wrapping_add(step[60]), stage_range[11]);
    out[4] = clamp_value(step[4].wrapping_add(step[59]), stage_range[11]);
    out[5] = clamp_value(step[5].wrapping_add(step[58]), stage_range[11]);
    out[6] = clamp_value(step[6].wrapping_add(step[57]), stage_range[11]);
    out[7] = clamp_value(step[7].wrapping_add(step[56]), stage_range[11]);
    out[8] = clamp_value(step[8].wrapping_add(step[55]), stage_range[11]);
    out[9] = clamp_value(step[9].wrapping_add(step[54]), stage_range[11]);
    out[10] = clamp_value(step[10].wrapping_add(step[53]), stage_range[11]);
    out[11] = clamp_value(step[11].wrapping_add(step[52]), stage_range[11]);
    out[12] = clamp_value(step[12].wrapping_add(step[51]), stage_range[11]);
    out[13] = clamp_value(step[13].wrapping_add(step[50]), stage_range[11]);
    out[14] = clamp_value(step[14].wrapping_add(step[49]), stage_range[11]);
    out[15] = clamp_value(step[15].wrapping_add(step[48]), stage_range[11]);
    out[16] = clamp_value(step[16].wrapping_add(step[47]), stage_range[11]);
    out[17] = clamp_value(step[17].wrapping_add(step[46]), stage_range[11]);
    out[18] = clamp_value(step[18].wrapping_add(step[45]), stage_range[11]);
    out[19] = clamp_value(step[19].wrapping_add(step[44]), stage_range[11]);
    out[20] = clamp_value(step[20].wrapping_add(step[43]), stage_range[11]);
    out[21] = clamp_value(step[21].wrapping_add(step[42]), stage_range[11]);
    out[22] = clamp_value(step[22].wrapping_add(step[41]), stage_range[11]);
    out[23] = clamp_value(step[23].wrapping_add(step[40]), stage_range[11]);
    out[24] = clamp_value(step[24].wrapping_add(step[39]), stage_range[11]);
    out[25] = clamp_value(step[25].wrapping_add(step[38]), stage_range[11]);
    out[26] = clamp_value(step[26].wrapping_add(step[37]), stage_range[11]);
    out[27] = clamp_value(step[27].wrapping_add(step[36]), stage_range[11]);
    out[28] = clamp_value(step[28].wrapping_add(step[35]), stage_range[11]);
    out[29] = clamp_value(step[29].wrapping_add(step[34]), stage_range[11]);
    out[30] = clamp_value(step[30].wrapping_add(step[33]), stage_range[11]);
    out[31] = clamp_value(step[31].wrapping_add(step[32]), stage_range[11]);
    out[32] = clamp_value(step[31].wrapping_sub(step[32]), stage_range[11]);
    out[33] = clamp_value(step[30].wrapping_sub(step[33]), stage_range[11]);
    out[34] = clamp_value(step[29].wrapping_sub(step[34]), stage_range[11]);
    out[35] = clamp_value(step[28].wrapping_sub(step[35]), stage_range[11]);
    out[36] = clamp_value(step[27].wrapping_sub(step[36]), stage_range[11]);
    out[37] = clamp_value(step[26].wrapping_sub(step[37]), stage_range[11]);
    out[38] = clamp_value(step[25].wrapping_sub(step[38]), stage_range[11]);
    out[39] = clamp_value(step[24].wrapping_sub(step[39]), stage_range[11]);
    out[40] = clamp_value(step[23].wrapping_sub(step[40]), stage_range[11]);
    out[41] = clamp_value(step[22].wrapping_sub(step[41]), stage_range[11]);
    out[42] = clamp_value(step[21].wrapping_sub(step[42]), stage_range[11]);
    out[43] = clamp_value(step[20].wrapping_sub(step[43]), stage_range[11]);
    out[44] = clamp_value(step[19].wrapping_sub(step[44]), stage_range[11]);
    out[45] = clamp_value(step[18].wrapping_sub(step[45]), stage_range[11]);
    out[46] = clamp_value(step[17].wrapping_sub(step[46]), stage_range[11]);
    out[47] = clamp_value(step[16].wrapping_sub(step[47]), stage_range[11]);
    out[48] = clamp_value(step[15].wrapping_sub(step[48]), stage_range[11]);
    out[49] = clamp_value(step[14].wrapping_sub(step[49]), stage_range[11]);
    out[50] = clamp_value(step[13].wrapping_sub(step[50]), stage_range[11]);
    out[51] = clamp_value(step[12].wrapping_sub(step[51]), stage_range[11]);
    out[52] = clamp_value(step[11].wrapping_sub(step[52]), stage_range[11]);
    out[53] = clamp_value(step[10].wrapping_sub(step[53]), stage_range[11]);
    out[54] = clamp_value(step[9].wrapping_sub(step[54]), stage_range[11]);
    out[55] = clamp_value(step[8].wrapping_sub(step[55]), stage_range[11]);
    out[56] = clamp_value(step[7].wrapping_sub(step[56]), stage_range[11]);
    out[57] = clamp_value(step[6].wrapping_sub(step[57]), stage_range[11]);
    out[58] = clamp_value(step[5].wrapping_sub(step[58]), stage_range[11]);
    out[59] = clamp_value(step[4].wrapping_sub(step[59]), stage_range[11]);
    out[60] = clamp_value(step[3].wrapping_sub(step[60]), stage_range[11]);
    out[61] = clamp_value(step[2].wrapping_sub(step[61]), stage_range[11]);
    out[62] = clamp_value(step[1].wrapping_sub(step[62]), stage_range[11]);
    out[63] = clamp_value(step[0].wrapping_sub(step[63]), stage_range[11]);
}

/// Bit-exact port of libaom `av1_iadst8` (transpiled, harness-verified).
#[allow(unused_variables)]
pub fn av1_iadst8(input: &[i32], out: &mut [i32], cos_bit: i32, stage_range: &[i8]) {
    let cospi = cospi_arr(cos_bit);
    let mut step = [0i32; 8];
    out[0] = input[7];
    out[1] = input[0];
    out[2] = input[5];
    out[3] = input[2];
    out[4] = input[3];
    out[5] = input[4];
    out[6] = input[1];
    out[7] = input[6];
    step[0] = half_btf(cospi[4], out[0], cospi[60], out[1], cos_bit);
    step[1] = half_btf(cospi[60], out[0], -cospi[4], out[1], cos_bit);
    step[2] = half_btf(cospi[20], out[2], cospi[44], out[3], cos_bit);
    step[3] = half_btf(cospi[44], out[2], -cospi[20], out[3], cos_bit);
    step[4] = half_btf(cospi[36], out[4], cospi[28], out[5], cos_bit);
    step[5] = half_btf(cospi[28], out[4], -cospi[36], out[5], cos_bit);
    step[6] = half_btf(cospi[52], out[6], cospi[12], out[7], cos_bit);
    step[7] = half_btf(cospi[12], out[6], -cospi[52], out[7], cos_bit);
    out[0] = clamp_value(step[0].wrapping_add(step[4]), stage_range[3]);
    out[1] = clamp_value(step[1].wrapping_add(step[5]), stage_range[3]);
    out[2] = clamp_value(step[2].wrapping_add(step[6]), stage_range[3]);
    out[3] = clamp_value(step[3].wrapping_add(step[7]), stage_range[3]);
    out[4] = clamp_value(step[0].wrapping_sub(step[4]), stage_range[3]);
    out[5] = clamp_value(step[1].wrapping_sub(step[5]), stage_range[3]);
    out[6] = clamp_value(step[2].wrapping_sub(step[6]), stage_range[3]);
    out[7] = clamp_value(step[3].wrapping_sub(step[7]), stage_range[3]);
    step[0] = out[0];
    step[1] = out[1];
    step[2] = out[2];
    step[3] = out[3];
    step[4] = half_btf(cospi[16], out[4], cospi[48], out[5], cos_bit);
    step[5] = half_btf(cospi[48], out[4], -cospi[16], out[5], cos_bit);
    step[6] = half_btf(-cospi[48], out[6], cospi[16], out[7], cos_bit);
    step[7] = half_btf(cospi[16], out[6], cospi[48], out[7], cos_bit);
    out[0] = clamp_value(step[0].wrapping_add(step[2]), stage_range[5]);
    out[1] = clamp_value(step[1].wrapping_add(step[3]), stage_range[5]);
    out[2] = clamp_value(step[0].wrapping_sub(step[2]), stage_range[5]);
    out[3] = clamp_value(step[1].wrapping_sub(step[3]), stage_range[5]);
    out[4] = clamp_value(step[4].wrapping_add(step[6]), stage_range[5]);
    out[5] = clamp_value(step[5].wrapping_add(step[7]), stage_range[5]);
    out[6] = clamp_value(step[4].wrapping_sub(step[6]), stage_range[5]);
    out[7] = clamp_value(step[5].wrapping_sub(step[7]), stage_range[5]);
    step[0] = out[0];
    step[1] = out[1];
    step[2] = half_btf(cospi[32], out[2], cospi[32], out[3], cos_bit);
    step[3] = half_btf(cospi[32], out[2], -cospi[32], out[3], cos_bit);
    step[4] = out[4];
    step[5] = out[5];
    step[6] = half_btf(cospi[32], out[6], cospi[32], out[7], cos_bit);
    step[7] = half_btf(cospi[32], out[6], -cospi[32], out[7], cos_bit);
    out[0] = step[0];
    out[1] = step[4].wrapping_neg();
    out[2] = step[6];
    out[3] = step[2].wrapping_neg();
    out[4] = step[3];
    out[5] = step[7].wrapping_neg();
    out[6] = step[5];
    out[7] = step[1].wrapping_neg();
}

/// Bit-exact port of libaom `av1_iadst16` (transpiled, harness-verified).
#[allow(unused_variables)]
pub fn av1_iadst16(input: &[i32], out: &mut [i32], cos_bit: i32, stage_range: &[i8]) {
    let cospi = cospi_arr(cos_bit);
    let mut step = [0i32; 16];
    out[0] = input[15];
    out[1] = input[0];
    out[2] = input[13];
    out[3] = input[2];
    out[4] = input[11];
    out[5] = input[4];
    out[6] = input[9];
    out[7] = input[6];
    out[8] = input[7];
    out[9] = input[8];
    out[10] = input[5];
    out[11] = input[10];
    out[12] = input[3];
    out[13] = input[12];
    out[14] = input[1];
    out[15] = input[14];
    step[0] = half_btf(cospi[2], out[0], cospi[62], out[1], cos_bit);
    step[1] = half_btf(cospi[62], out[0], -cospi[2], out[1], cos_bit);
    step[2] = half_btf(cospi[10], out[2], cospi[54], out[3], cos_bit);
    step[3] = half_btf(cospi[54], out[2], -cospi[10], out[3], cos_bit);
    step[4] = half_btf(cospi[18], out[4], cospi[46], out[5], cos_bit);
    step[5] = half_btf(cospi[46], out[4], -cospi[18], out[5], cos_bit);
    step[6] = half_btf(cospi[26], out[6], cospi[38], out[7], cos_bit);
    step[7] = half_btf(cospi[38], out[6], -cospi[26], out[7], cos_bit);
    step[8] = half_btf(cospi[34], out[8], cospi[30], out[9], cos_bit);
    step[9] = half_btf(cospi[30], out[8], -cospi[34], out[9], cos_bit);
    step[10] = half_btf(cospi[42], out[10], cospi[22], out[11], cos_bit);
    step[11] = half_btf(cospi[22], out[10], -cospi[42], out[11], cos_bit);
    step[12] = half_btf(cospi[50], out[12], cospi[14], out[13], cos_bit);
    step[13] = half_btf(cospi[14], out[12], -cospi[50], out[13], cos_bit);
    step[14] = half_btf(cospi[58], out[14], cospi[6], out[15], cos_bit);
    step[15] = half_btf(cospi[6], out[14], -cospi[58], out[15], cos_bit);
    out[0] = clamp_value(step[0].wrapping_add(step[8]), stage_range[3]);
    out[1] = clamp_value(step[1].wrapping_add(step[9]), stage_range[3]);
    out[2] = clamp_value(step[2].wrapping_add(step[10]), stage_range[3]);
    out[3] = clamp_value(step[3].wrapping_add(step[11]), stage_range[3]);
    out[4] = clamp_value(step[4].wrapping_add(step[12]), stage_range[3]);
    out[5] = clamp_value(step[5].wrapping_add(step[13]), stage_range[3]);
    out[6] = clamp_value(step[6].wrapping_add(step[14]), stage_range[3]);
    out[7] = clamp_value(step[7].wrapping_add(step[15]), stage_range[3]);
    out[8] = clamp_value(step[0].wrapping_sub(step[8]), stage_range[3]);
    out[9] = clamp_value(step[1].wrapping_sub(step[9]), stage_range[3]);
    out[10] = clamp_value(step[2].wrapping_sub(step[10]), stage_range[3]);
    out[11] = clamp_value(step[3].wrapping_sub(step[11]), stage_range[3]);
    out[12] = clamp_value(step[4].wrapping_sub(step[12]), stage_range[3]);
    out[13] = clamp_value(step[5].wrapping_sub(step[13]), stage_range[3]);
    out[14] = clamp_value(step[6].wrapping_sub(step[14]), stage_range[3]);
    out[15] = clamp_value(step[7].wrapping_sub(step[15]), stage_range[3]);
    step[0] = out[0];
    step[1] = out[1];
    step[2] = out[2];
    step[3] = out[3];
    step[4] = out[4];
    step[5] = out[5];
    step[6] = out[6];
    step[7] = out[7];
    step[8] = half_btf(cospi[8], out[8], cospi[56], out[9], cos_bit);
    step[9] = half_btf(cospi[56], out[8], -cospi[8], out[9], cos_bit);
    step[10] = half_btf(cospi[40], out[10], cospi[24], out[11], cos_bit);
    step[11] = half_btf(cospi[24], out[10], -cospi[40], out[11], cos_bit);
    step[12] = half_btf(-cospi[56], out[12], cospi[8], out[13], cos_bit);
    step[13] = half_btf(cospi[8], out[12], cospi[56], out[13], cos_bit);
    step[14] = half_btf(-cospi[24], out[14], cospi[40], out[15], cos_bit);
    step[15] = half_btf(cospi[40], out[14], cospi[24], out[15], cos_bit);
    out[0] = clamp_value(step[0].wrapping_add(step[4]), stage_range[5]);
    out[1] = clamp_value(step[1].wrapping_add(step[5]), stage_range[5]);
    out[2] = clamp_value(step[2].wrapping_add(step[6]), stage_range[5]);
    out[3] = clamp_value(step[3].wrapping_add(step[7]), stage_range[5]);
    out[4] = clamp_value(step[0].wrapping_sub(step[4]), stage_range[5]);
    out[5] = clamp_value(step[1].wrapping_sub(step[5]), stage_range[5]);
    out[6] = clamp_value(step[2].wrapping_sub(step[6]), stage_range[5]);
    out[7] = clamp_value(step[3].wrapping_sub(step[7]), stage_range[5]);
    out[8] = clamp_value(step[8].wrapping_add(step[12]), stage_range[5]);
    out[9] = clamp_value(step[9].wrapping_add(step[13]), stage_range[5]);
    out[10] = clamp_value(step[10].wrapping_add(step[14]), stage_range[5]);
    out[11] = clamp_value(step[11].wrapping_add(step[15]), stage_range[5]);
    out[12] = clamp_value(step[8].wrapping_sub(step[12]), stage_range[5]);
    out[13] = clamp_value(step[9].wrapping_sub(step[13]), stage_range[5]);
    out[14] = clamp_value(step[10].wrapping_sub(step[14]), stage_range[5]);
    out[15] = clamp_value(step[11].wrapping_sub(step[15]), stage_range[5]);
    step[0] = out[0];
    step[1] = out[1];
    step[2] = out[2];
    step[3] = out[3];
    step[4] = half_btf(cospi[16], out[4], cospi[48], out[5], cos_bit);
    step[5] = half_btf(cospi[48], out[4], -cospi[16], out[5], cos_bit);
    step[6] = half_btf(-cospi[48], out[6], cospi[16], out[7], cos_bit);
    step[7] = half_btf(cospi[16], out[6], cospi[48], out[7], cos_bit);
    step[8] = out[8];
    step[9] = out[9];
    step[10] = out[10];
    step[11] = out[11];
    step[12] = half_btf(cospi[16], out[12], cospi[48], out[13], cos_bit);
    step[13] = half_btf(cospi[48], out[12], -cospi[16], out[13], cos_bit);
    step[14] = half_btf(-cospi[48], out[14], cospi[16], out[15], cos_bit);
    step[15] = half_btf(cospi[16], out[14], cospi[48], out[15], cos_bit);
    out[0] = clamp_value(step[0].wrapping_add(step[2]), stage_range[7]);
    out[1] = clamp_value(step[1].wrapping_add(step[3]), stage_range[7]);
    out[2] = clamp_value(step[0].wrapping_sub(step[2]), stage_range[7]);
    out[3] = clamp_value(step[1].wrapping_sub(step[3]), stage_range[7]);
    out[4] = clamp_value(step[4].wrapping_add(step[6]), stage_range[7]);
    out[5] = clamp_value(step[5].wrapping_add(step[7]), stage_range[7]);
    out[6] = clamp_value(step[4].wrapping_sub(step[6]), stage_range[7]);
    out[7] = clamp_value(step[5].wrapping_sub(step[7]), stage_range[7]);
    out[8] = clamp_value(step[8].wrapping_add(step[10]), stage_range[7]);
    out[9] = clamp_value(step[9].wrapping_add(step[11]), stage_range[7]);
    out[10] = clamp_value(step[8].wrapping_sub(step[10]), stage_range[7]);
    out[11] = clamp_value(step[9].wrapping_sub(step[11]), stage_range[7]);
    out[12] = clamp_value(step[12].wrapping_add(step[14]), stage_range[7]);
    out[13] = clamp_value(step[13].wrapping_add(step[15]), stage_range[7]);
    out[14] = clamp_value(step[12].wrapping_sub(step[14]), stage_range[7]);
    out[15] = clamp_value(step[13].wrapping_sub(step[15]), stage_range[7]);
    step[0] = out[0];
    step[1] = out[1];
    step[2] = half_btf(cospi[32], out[2], cospi[32], out[3], cos_bit);
    step[3] = half_btf(cospi[32], out[2], -cospi[32], out[3], cos_bit);
    step[4] = out[4];
    step[5] = out[5];
    step[6] = half_btf(cospi[32], out[6], cospi[32], out[7], cos_bit);
    step[7] = half_btf(cospi[32], out[6], -cospi[32], out[7], cos_bit);
    step[8] = out[8];
    step[9] = out[9];
    step[10] = half_btf(cospi[32], out[10], cospi[32], out[11], cos_bit);
    step[11] = half_btf(cospi[32], out[10], -cospi[32], out[11], cos_bit);
    step[12] = out[12];
    step[13] = out[13];
    step[14] = half_btf(cospi[32], out[14], cospi[32], out[15], cos_bit);
    step[15] = half_btf(cospi[32], out[14], -cospi[32], out[15], cos_bit);
    out[0] = step[0];
    out[1] = step[8].wrapping_neg();
    out[2] = step[12];
    out[3] = step[4].wrapping_neg();
    out[4] = step[6];
    out[5] = step[14].wrapping_neg();
    out[6] = step[10];
    out[7] = step[2].wrapping_neg();
    out[8] = step[3];
    out[9] = step[11].wrapping_neg();
    out[10] = step[15];
    out[11] = step[7].wrapping_neg();
    out[12] = step[5];
    out[13] = step[13].wrapping_neg();
    out[14] = step[9];
    out[15] = step[1].wrapping_neg();
}
